import { useCallback, useEffect, useMemo, useRef, useState } from "react"
import { Head, Link, router, useHttp, usePage } from "@inertiajs/react"
import {
  IconArrowLeft,
  IconCheck,
  IconClock,
  IconDotsVertical,
  IconFlame,
  IconSparkles,
} from "@tabler/icons-react"

import HtmlDiff from "htmldiff-js"
import TurndownService from "turndown"

import type { SharedProps } from "@/types"
import type { Postmortem, PostmortemUpdate } from "@/types/serializers"
import { PostmortemEditor } from "@/pages/incidents/components/postmortem-editor"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"
import { Separator } from "@/components/ui/separator"
import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetHeader,
  SheetTitle,
} from "@/components/ui/sheet"
import { Skeleton } from "@/components/ui/skeleton"
import { incidentPath, incidentPostmortemPath, incidentPostmortemRevisionsPath, incidentPostmortemStatusPath } from "@/lib/routes"

const statusLabels: Record<string, string> = {
  draft: "Draft",
  in_progress: "In progress",
  in_review: "In review",
  completed: "Completed",
}

const statusStyles: Record<string, string> = {
  draft: "bg-muted text-muted-foreground",
  in_progress: "bg-amber-500/15 text-amber-600 dark:text-amber-400",
  in_review: "bg-blue-500/15 text-blue-600 dark:text-blue-400",
  completed: "bg-emerald-500/15 text-emerald-600 dark:text-emerald-400",
}

const updateTypeLabels: Record<string, string> = {
  generated: "Generated by AI",
  edited: "Edited",
  ai_edited: "AI rewritten",
}

interface PostmortemPageProps extends SharedProps {
  incident: { id: string; identifier: string; name: string }
  postmortem: Postmortem | null
}

function RevisionsSheet({
  incidentId,
  currentHtml,
  open,
  onOpenChange,
  onRestore,
}: {
  incidentId: string
  currentHtml: string
  open: boolean
  onOpenChange: (open: boolean) => void
  onRestore: (html: string) => void
}) {
  const [revisions, setRevisions] = useState<PostmortemUpdate[]>([])
  const [loading, setLoading] = useState(false)
  const [selectedId, setSelectedId] = useState<string | null>(null)

  useEffect(() => {
    if (open && revisions.length === 0) {
      setLoading(true)
      fetch(incidentPostmortemRevisionsPath(incidentId))
        .then((res) => res.json())
        .then((data) => {
          setRevisions(data)
          setLoading(false)
        })
        .catch(() => setLoading(false))
    }
  }, [open, incidentId]) // eslint-disable-line react-hooks/exhaustive-deps

  const selectedRevision = selectedId ? revisions.find((r) => r.id === selectedId) : null
  const selectedIndex = selectedRevision ? revisions.indexOf(selectedRevision) : -1

  const diffHtml = useMemo(() => {
    if (!selectedRevision?.htmlContent) return null
    const olderHtml = selectedRevision.htmlContent
    // revisions are newest-first, so the "next" version is the one before it in the array (index - 1)
    // or the current editor content if this is the most recent revision
    const newerHtml = selectedIndex === 0 ? currentHtml : (revisions[selectedIndex - 1]?.htmlContent ?? currentHtml)
    try {
      return HtmlDiff.execute(olderHtml, newerHtml)
    } catch {
      return null
    }
  }, [selectedRevision, selectedIndex, revisions, currentHtml])

  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent className="sm:max-w-lg overflow-y-auto">
        <SheetHeader>
          <SheetTitle>Revisions</SheetTitle>
          <SheetDescription>
            {selectedRevision ? "Viewing revision" : "Select a revision to preview"}
          </SheetDescription>
        </SheetHeader>
        <div className="flex flex-col gap-4 px-6 pb-6">
          {loading && (
            <div className="space-y-3">
              {Array.from({ length: 4 }).map((_, i) => (
                <Skeleton key={i} className="h-12 w-full" />
              ))}
            </div>
          )}

          {!loading && !selectedRevision && (
            <div className="space-y-1">
              {revisions.map((rev) => (
                <button
                  key={rev.id}
                  onClick={() => setSelectedId(rev.id)}
                  className="flex w-full items-center gap-3 rounded-lg border p-3 text-left hover:bg-muted/50 transition-colors"
                >
                  <IconClock className="size-4 text-muted-foreground shrink-0" />
                  <div className="flex-1 min-w-0">
                    <div className="text-sm font-medium">{rev.editedBy}</div>
                    <div className="text-xs text-muted-foreground">
                      {updateTypeLabels[rev.updateType] ?? rev.updateType}
                    </div>
                  </div>
                  <span className="text-xs text-muted-foreground tabular-nums shrink-0">
                    {new Date(rev.createdAt).toLocaleDateString("en-US", {
                      month: "short", day: "numeric", hour: "2-digit", minute: "2-digit",
                    })}
                  </span>
                </button>
              ))}
              {revisions.length === 0 && (
                <p className="text-sm text-muted-foreground text-center py-8">
                  No revisions yet.
                </p>
              )}
            </div>
          )}

          {selectedRevision && (
            <div className="flex flex-col gap-4">
              <div className="flex items-center justify-between">
                <Button variant="ghost" size="sm" onClick={() => setSelectedId(null)}>
                  <IconArrowLeft className="size-3" />
                  Back
                </Button>
                <Button
                  size="sm"
                  onClick={() => {
                    if (selectedRevision.htmlContent) {
                      onRestore(selectedRevision.htmlContent)
                      onOpenChange(false)
                      setSelectedId(null)
                    }
                  }}
                  disabled={!selectedRevision.htmlContent}
                >
                  Restore this version
                </Button>
              </div>
              <div className="flex items-center gap-2 text-sm text-muted-foreground">
                <span className="font-medium text-foreground">{selectedRevision.editedBy}</span>
                <span>·</span>
                <span>{updateTypeLabels[selectedRevision.updateType]}</span>
                <span>·</span>
                <span>
                  {new Date(selectedRevision.createdAt).toLocaleDateString("en-US", {
                    month: "short", day: "numeric", hour: "2-digit", minute: "2-digit",
                  })}
                </span>
              </div>
              <Separator />
              {diffHtml ? (
                <div
                  className="prose prose-sm dark:prose-invert max-w-none rounded-lg border p-4 bg-muted [&_ins]:bg-emerald-500/20 [&_ins]:text-emerald-900 [&_ins]:no-underline [&_ins]:px-0.5 [&_ins]:rounded-sm dark:[&_ins]:text-emerald-300 [&_del]:bg-red-500/20 [&_del]:text-red-900 [&_del]:line-through [&_del]:px-0.5 [&_del]:rounded-sm dark:[&_del]:text-red-300"
                  dangerouslySetInnerHTML={{ __html: diffHtml }}
                />
              ) : selectedRevision.htmlContent ? (
                <div
                  className="prose prose-sm dark:prose-invert max-w-none rounded-lg border p-4 bg-muted"
                  dangerouslySetInnerHTML={{ __html: selectedRevision.htmlContent }}
                />
              ) : (
                <p className="text-sm text-muted-foreground text-center py-8">
                  No content snapshot available for this revision.
                </p>
              )}
            </div>
          )}
        </div>
      </SheetContent>
    </Sheet>
  )
}

export default function PostmortemPage() {
  const { incident, postmortem } = usePage<PostmortemPageProps>().props

  if (!postmortem) {
    return (
      <>
        <Head title={`Postmortem — ${incident.identifier}`} />
        <div className="flex min-h-screen items-center justify-center">
          <div className="text-center text-muted-foreground">
            <p>No postmortem has been generated for this incident yet.</p>
            <Link href={incidentPath(incident.id)} className="mt-4 inline-block text-primary hover:underline">
              Back to incident
            </Link>
          </div>
        </div>
      </>
    )
  }

  return <PostmortemView incident={incident} postmortem={postmortem} />
}

function PostmortemView({
  incident,
  postmortem,
}: {
  incident: PostmortemPageProps["incident"]
  postmortem: Postmortem
}) {
  const saveTimerRef = useRef<ReturnType<typeof setTimeout>>()
  const { setData, patch, processing, recentlySuccessful } = useHttp({ html_content: "" })
  const [editorKey, setEditorKey] = useState(0)
  const [revisionsOpen, setRevisionsOpen] = useState(false)
  const editorContentRef = useRef(postmortem.htmlContent ?? "")

  const handleContentUpdate = useCallback((html: string) => {
    editorContentRef.current = html
    clearTimeout(saveTimerRef.current)
    setData("html_content", html)
    saveTimerRef.current = setTimeout(() => {
      saveTimerRef.current = undefined
      patch(incidentPostmortemPath(incident.id))
    }, 1500)
  }, [incident.id, setData, patch])

  const handleRestore = useCallback((html: string) => {
    editorContentRef.current = html
    setEditorKey((k) => k + 1)
    setData("html_content", html)
    patch(incidentPostmortemPath(incident.id))
  }, [incident.id, setData, patch])

  const handleExportMarkdown = useCallback(() => {
    const turndown = new TurndownService({ headingStyle: "atx", codeBlockStyle: "fenced" })
    const title = `# ${postmortem.title}\n\n> ${incident.identifier} — ${incident.name}\n\n`
    const markdown = title + turndown.turndown(editorContentRef.current || "")
    const blob = new Blob([markdown], { type: "text/markdown" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `${incident.identifier}-postmortem.md`
    a.click()
    URL.revokeObjectURL(url)
  }, [incident, postmortem.title])

  useEffect(() => {
    const flushPendingSave = () => {
      if (!saveTimerRef.current) return
      clearTimeout(saveTimerRef.current)
      saveTimerRef.current = undefined

      const csrfToken = document.querySelector('meta[name="csrf-token"]')?.getAttribute('content')
      fetch(incidentPostmortemPath(incident.id), {
        method: 'PATCH',
        headers: {
          'Content-Type': 'application/json',
          ...(csrfToken ? { 'X-CSRF-Token': csrfToken } : {}),
        },
        body: JSON.stringify({ html_content: editorContentRef.current }),
        keepalive: true,
      })
    }

    const removeListener = router.on('before', flushPendingSave)
    return () => {
      removeListener()
      flushPendingSave()
    }
  }, [incident.id])

  return (
    <>
      <Head title={`Postmortem — ${incident.identifier}`} />
      <div className="min-h-screen bg-background">
        <header className="sticky top-0 z-50 border-b bg-background print:hidden">
          <div className="mx-auto flex h-12 max-w-4xl items-center gap-3 px-4 lg:px-6">
            <Link href={incidentPath(incident.id)} className="text-muted-foreground hover:text-foreground">
              <IconArrowLeft className="size-4" />
            </Link>
            <Separator orientation="vertical" className="h-4" />
            <nav className="flex items-center gap-1.5 text-sm text-muted-foreground overflow-hidden">
              <IconFlame className="size-4 shrink-0 text-primary" />
              <span className="hidden sm:inline">Incidents</span>
              <span className="hidden sm:inline">›</span>
              <span className="font-medium hidden sm:inline">{incident.identifier}</span>
              <span className="hidden sm:inline">›</span>
              <span className="truncate font-medium text-foreground">
                Postmortem
              </span>
            </nav>
            <div className="ml-auto flex items-center gap-2">
              {recentlySuccessful && (
                <span className="flex items-center gap-1 text-xs text-emerald-600 dark:text-emerald-400">
                  <IconCheck className="size-3" />
                  Saved
                </span>
              )}
              {processing && (
                <span className="text-xs text-muted-foreground">Saving...</span>
              )}
              <Badge
                variant="secondary"
                className={`text-xs ${statusStyles[postmortem.status]}`}
              >
                {statusLabels[postmortem.status]}
              </Badge>
              <Button variant="outline" size="sm" onClick={() => setRevisionsOpen(true)}>
                <IconClock className="size-4" />
                Revisions
              </Button>
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button variant="ghost" size="icon" className="size-8">
                    <IconDotsVertical className="size-4" />
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end">
                  <DropdownMenuItem onClick={() => window.print()}>Export as PDF</DropdownMenuItem>
                  <DropdownMenuItem onClick={handleExportMarkdown}>Export as Markdown</DropdownMenuItem>
                  <DropdownMenuSeparator />
                  <DropdownMenuItem>
                    <IconSparkles className="size-4" />
                    AI Rewrite
                  </DropdownMenuItem>
                  <DropdownMenuSeparator />
                  {postmortem.status !== "completed" ? (
                    <DropdownMenuItem onClick={() => router.patch(incidentPostmortemStatusPath(incident.id), { status: "completed" })}>
                      Mark as Completed
                    </DropdownMenuItem>
                  ) : (
                    <DropdownMenuItem onClick={() => router.patch(incidentPostmortemStatusPath(incident.id), { status: "draft" })}>
                      Reopen as Draft
                    </DropdownMenuItem>
                  )}
                </DropdownMenuContent>
              </DropdownMenu>
            </div>
          </div>
        </header>

        <main className="mx-auto max-w-3xl px-4 py-12 lg:px-6 print:px-0 print:py-0 print:max-w-none">
          <div className="hidden print:block mb-8">
            <h1 className="text-2xl font-bold">{postmortem.title}</h1>
            <p className="text-sm text-muted-foreground mt-1">{incident.identifier} — {incident.name}</p>
          </div>
          <PostmortemEditor
            key={editorKey}
            content={editorContentRef.current || undefined}
            onUpdate={handleContentUpdate}
          />
        </main>
      </div>

      <RevisionsSheet
        incidentId={incident.id}
        currentHtml={editorContentRef.current}
        open={revisionsOpen}
        onOpenChange={setRevisionsOpen}
        onRestore={handleRestore}
      />
    </>
  )
}
