import {
  type Icon,
  IconArrowsRightLeft,
  IconArrowsSplit,
  IconBolt,
  IconBrowser,
  IconBucket,
  IconClockPlay,
  IconCode,
  IconDatabase,
  IconGitBranch,
  IconHammer,
  IconKey,
  IconPlugConnected,
  IconServer2,
  IconServerCog,
  IconShieldLock,
  IconStack2,
  IconWorld,
  IconWorldWww,
} from "@tabler/icons-react"

import type { ResourceMapKind } from "@/lib/generated/constants"

export const KIND_ICONS: Record<ResourceMapKind, Icon> = {
  service: IconServer2,
  build_service: IconHammer,
  job: IconClockPlay,
  database: IconDatabase,
  branch: IconGitBranch,
  repository: IconCode,
  domain: IconWorldWww,
  zone: IconWorld,
  worker: IconBolt,
  site: IconBrowser,
  bucket: IconBucket,
  kv_namespace: IconKey,
  queue: IconStack2,
  database_proxy: IconPlugConnected,
  tunnel: IconArrowsRightLeft,
  load_balancer: IconArrowsSplit,
  origin_pool: IconServerCog,
  access_app: IconShieldLock,
}
