import {
  type Icon,
  IconArrowsRightLeft,
  IconArrowsSplit,
  IconBolt,
  IconBrowser,
  IconBucket,
  IconClockPlay,
  IconCloudComputing,
  IconCode,
  IconCpu,
  IconDatabase,
  IconGitBranch,
  IconHammer,
  IconKey,
  IconLambda,
  IconPlugConnected,
  IconServer2,
  IconServerCog,
  IconShieldLock,
  IconStack2,
  IconTopologyStar3,
  IconWorld,
  IconWorldWww,
} from "@tabler/icons-react"

import type { ResourceMapKind } from "@/lib/generated/constants"

export const KIND_ICONS: Record<ResourceMapKind, Icon> = {
  service: IconServer2,
  build_service: IconHammer,
  job: IconClockPlay,
  database: IconDatabase,
  branch: IconGitBranch,
  repository: IconCode,
  domain: IconWorldWww,
  zone: IconWorld,
  worker: IconBolt,
  site: IconBrowser,
  bucket: IconBucket,
  kv_namespace: IconKey,
  queue: IconStack2,
  database_proxy: IconPlugConnected,
  tunnel: IconArrowsRightLeft,
  load_balancer: IconArrowsSplit,
  origin_pool: IconServerCog,
  access_app: IconShieldLock,
  virtual_machine: IconCloudComputing,
  function: IconLambda,
  cluster: IconTopologyStar3,
  compute: IconCpu,
}

export const KIND_LABELS: Record<ResourceMapKind, string> = {
  service: "Service",
  build_service: "Build service",
  job: "Job",
  database: "Database",
  branch: "Database branch",
  repository: "Repository",
  domain: "Domain",
  zone: "Zone",
  worker: "Worker",
  site: "Static site",
  bucket: "Bucket",
  kv_namespace: "Key value store",
  queue: "Queue",
  database_proxy: "Database proxy",
  tunnel: "Tunnel",
  load_balancer: "Load balancer",
  origin_pool: "Origin pool",
  access_app: "Access policy",
  virtual_machine: "Virtual machine",
  function: "Function",
  cluster: "Cluster",
  compute: "Compute",
}
