display_information:
  name: Firefight (Development)
  description: Firefight development environment
  background_color: "#000000"

features:
  bot_user:
    display_name: Firefight Bot
    always_online: false
  slash_commands:
    - command: /firefight
      url: https://br9xk9-ip-95-180-89-16.tunnelmole.net/api/v1/commands
      description: Firefight incident management
      usage_hint: "[subcommand]"
    - command: /ff
      url: https://br9xk9-ip-95-180-89-16.tunnelmole.net/api/v1/commands
      description: Firefight (short alias)
      usage_hint: "[subcommand]"

oauth_config:
  redirect_urls:
    - http://localhost:3000/auth/slack/callback
    - https://br9xk9-ip-95-180-89-16.tunnelmole.net/auth/slack/callback
  scopes:
    user:
      - users:read
      - users:read.email
    bot:
      - team:read
      - commands
      - chat:write

settings:
  interactivity:
    is_enabled: true
    request_url: https://br9xk9-ip-95-180-89-16.tunnelmole.net/api/v1/interactions
  org_deploy_enabled: false
  socket_mode_enabled: false
  token_rotation_enabled: true
