// TypesFromSerializers CacheKey 438f73e333e254f6b2bcf4cdb29aa6c8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface OperatorAttentionItem {
  at: string
  detail?: string
  external: boolean
  href?: string
  key: string
  kind: "workflow_failed" | "workflow_stuck" | "webhook_failing" | "platform_failed" | "alert_stuck" | "queue_backed_up" | "jobs_failed" | "halon_failed" | "halon_limit" | "halon_not_posted" | "halon_stuck" | "skill_broken" | "ai_out_of_credit" | "ai_short_of_credit" | "ai_balance_unchecked" | "sandbox_failover" | "sandbox_rogue" | "sandbox_trouble" | "sandbox_unread"
  place: string
  subject: string
  title: string
  tone: "ok" | "info" | "warn" | "bad" | "idle"
}
