// TypesFromSerializers CacheKey ec7fd6b0d5f82424b76052c337edb23a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface OperatorAttentionItem {
  at: string
  detail?: string
  external: boolean
  href?: string
  key: string
  kind: "workflow_failed" | "workflow_stuck" | "webhook_failing" | "platform_failed" | "alert_stuck" | "queue_backed_up" | "jobs_failed" | "halon_failed" | "halon_limit" | "halon_not_posted" | "halon_stuck"
  place: string
  subject: string
  title: string
  tone: "ok" | "info" | "warn" | "bad" | "idle"
}
