// TypesFromSerializers CacheKey 2cefcaf1754fad8a7dcdfb417fbad8d9
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface OperatorAttentionItem {
  at: string
  detail?: string
  external: boolean
  href?: string
  key: string
  kind: "workflow_failed" | "workflow_stuck" | "webhook_failing" | "platform_failed" | "alert_stuck" | "queue_backed_up" | "jobs_failed" | "halon_failed" | "halon_limit" | "halon_not_posted" | "halon_stuck" | "skill_broken" | "ai_out_of_credit" | "ai_short_of_credit" | "ai_balance_unchecked" | "sandbox_failover"
  place: string
  subject: string
  title: string
  tone: "ok" | "info" | "warn" | "bad" | "idle"
}
