// TypesFromSerializers CacheKey 37f10edd2b981f3750268e1923bc4b56
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface OperatorFindMatch {
  id: string
  href: string
  kind: "incident" | "run" | "chat" | "workflow" | "bench"
  label: string
  place: string
  via?: string
}
