// TypesFromSerializers CacheKey a415a1be09508eebb98898ef7c05c45d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface OperatorFindMatch {
  id: string
  href: string
  kind: "incident" | "run" | "chat" | "workflow"
  label: string
  place: string
  via?: string
}
