// TypesFromSerializers CacheKey 55545a6802c2fafa4ea04769ea63660e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface OperatorHalonRegressionRun {
  id: string
  createdAt: string
  errored: number
  failed: number
  finishedAt?: string
  model?: string
  passed: number
  pending: number
  promptVersion: string
  skipped: number
  startedBy?: string
  status: "running" | "finished"
  total: number
  trigger: "prompt_change" | "operator"
}
