// TypesFromSerializers CacheKey e5f8e532c19c65457131d10641243469
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface OperatorHalonRegressionCase {
  id: string
  answer?: string
  expected: "confirmed" | "wrong"
  label: string
  newlyFailing: boolean
  originalId: string
  previousStatus?: "pending" | "passed" | "failed" | "errored" | "skipped"
  ratedAnswer: string
  reason?: string
  replayId?: string
  spentMicros: number
  status: "pending" | "passed" | "failed" | "errored" | "skipped"
  workspaceName: string
}
