// TypesFromSerializers CacheKey 6f70b60277e0c554eb526b6b2fdf9fde
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface OperatorHalonChat {
  id: string
  incidentLabel?: string
  kind: "channel" | "personal" | "mcp"
  spentMicros: number
  title: string
  turns: number
  updatedAt: string
  workspaceName: string
}
