// TypesFromSerializers CacheKey 9042453ef2003a1e1fd0c577d25e6bb3
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface OperatorHalonRegressionModel {
  id: string
  name: string
  provider: string
}
