// TypesFromSerializers CacheKey 0fdd0a3bf38783790295979b2452dd98
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface OperatorHalonRun {
  id: string
  completedAt?: string
  conversationId?: string
  createdAt: string
  ending: "answered" | "stopped" | "failed" | "live"
  errorSummary?: string
  incidentId?: string
  label: string
  maxSpendMicros: number
  maxTurns: number
  notPosted: boolean
  rehearsal: boolean
  seconds?: number
  spentMicros: number
  status: string
  stoppedBecause?: string
  triggerSource: string
  turns: number
  workspaceName: string
}
