// TypesFromSerializers CacheKey 9c1188f97880c4eff6ebd6218055ec5f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface OperatorIncidentRow {
  id: string
  declaredAt?: string
  identifier: string
  name: string
  problems: number
  status: string
  workspaceName: string
}
