// TypesFromSerializers CacheKey 6da9be01a0b1341484404f636d6ddaa4
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface OperatorSandboxFailover {
  id: string
  at: string
  from: string
  reason: string
  to: string
}
