// TypesFromSerializers CacheKey 68fccbf55e6af49c7028bc96b916f1ca
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface OperatorSandboxBox {
  adoptBlockedReason?: string
  costMicros?: number
  endedAt?: string
  flags: ("rogue" | "overdue" | "failed" | "stuck" | "missing")[]
  held: boolean
  key: string
  lastUsedAt?: string
  name?: string
  origin: { kind: "investigation" | "chat" | "code_fix" | "other"; label: string; href: string | null } | null
  phase?: "starting" | "running" | "stopping" | "stopped" | "ready" | "failed"
  provider: string
  providerName: string
  recorded: boolean
  ref: string
  seconds: number
  size?: string
  startedAt?: string
  state?: string
  workspaceId?: string
  workspaceName?: string
}
