// TypesFromSerializers CacheKey 4218a3ad57b329679cdbc1cd8a6556c9
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface OperatorSandboxAction {
  id: string
  actionName: "stop" | "delete" | "clean_up"
  at: string
  operator: string
  outcome?: string
  providerName: string
  ref: string
}
