// TypesFromSerializers CacheKey fdc33af3d525f5f379aa2aae4c1e939b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface OperatorSandboxTotals {
  failovers: number
  monthMicros: number
  rogue: number
  running: { provider: string; name: string; count: number }[]
  todayMicros: number
}
