// TypesFromSerializers CacheKey 4586b5e9440715e82925bd50e26c4242
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface OperatorSandboxFix {
  id: string
  aiMicros: number
  at: string
  providers: string[]
  pullRequestUrl?: string
  repository: string
  sandboxMicros?: number
  sandboxSeconds: number
}
