// TypesFromSerializers CacheKey 7f326849a50460736de8fb01e53d6454
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface OperatorSandboxCopy {
  byteSize?: number
  createdAt?: string
  flags: ("rogue" | "overdue" | "failed" | "stuck" | "missing")[]
  key: string
  lastUsedAt?: string
  monthlyMicros: number
  phase?: string
  provider: string
  providerName: string
  purpose: "image" | "prepared" | "run"
  ref: string
  repository?: string
  state?: string
  workspaceName?: string
}
