// TypesFromSerializers CacheKey 9f6f502ef2d739163f09f7c563baaf4f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface OperatorSandboxAction {
  id: string
  actionName: "stop" | "delete" | "clean_up" | "adopt"
  at: string
  operator: string
  outcome?: string
  providerName: string
  ref: string
}
