// TypesFromSerializers CacheKey cc9204627a015c004de69674b8e2d822
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type OperatorTraceSpan from './TraceSpan'

export default interface OperatorTraceGroup {
  endedAt?: string
  key: string
  spans: OperatorTraceSpan[]
  startedAt?: string
  title: string
}
