// TypesFromSerializers CacheKey af731ade2c31cb0a939ecb4165bb1852
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface OperatorWorkflow {
  id: string
  cancelBlockedReason?: string
  cancellationReason?: string
  createdAt: string
  events: { id: string; at: string; eventType: string; stepName: string | null; note: string | null; failed: boolean }[]
  failedStep?: string
  incidentId?: string
  pauseBlockedReason?: string
  pauseReason?: string
  resumeBlockedReason?: string
  state: "pending" | "running" | "paused" | "succeeded" | "failed" | "cancelled"
  steps: { id: string; name: string; status: "pending" | "running" | "succeeded" | "failed" | "skipped" | "cancelled"; attempts: number; maxAttempts: number | null; lastError: string | null; skipReason: string | null; seconds: number | null; dependsOn: string[]; column: number; row: number; actionBlockedReason: string | null }[]
  stepsDone: number
  stepsTotal: number
  subjectLabel: string
  workflowClass: string
}
