// TypesFromSerializers CacheKey c2bc3ca2e50c971c1f95e2bfbe992914
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface OperatorWorkflowRow {
  id: string
  createdAt: string
  failedStep?: string
  incidentId?: string
  state: "pending" | "running" | "paused" | "succeeded" | "failed" | "cancelled"
  stepsDone: number
  stepsTotal: number
  subjectLabel: string
  workflowClass: string
}
