// TypesFromSerializers CacheKey 51640665bb4b1412a974b80d99313cc9
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface OperatorWorkspaceRow {
  id: string
  boxes: number
  createdAt: string
  failovers: number
  held: boolean
  name: string
  placement: string
  sandboxMicros: number
}
