// TypesFromSerializers CacheKey 1f2fd16bf8761b7bce59f841baeca731
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AbilityInvocation {
  id: string
  actionKey: string
  approvalId?: string
  completedAt?: string
  createdAt: string
  decision: "allow" | "deny" | "pending"
  durationMs?: number
  errorSummary?: string
  outcome?: "success" | "error"
  principalLabel: string
  riskLevel?: string
  scope: Record<string, string[]>
  source?: string
  triggeredByLabel?: string
}
