// TypesFromSerializers CacheKey a4dc07130d0d396b49cc34d5d57d839b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AbilityApproval {
  id: string
  actionKey: string
  approverName?: string
  createdAt: string
  params: Record<string, unknown>
  principalLabel: string
  requiredRole: string
  resolvedAt?: string
  scope: Record<string, string[]>
  selfApprovable: boolean
  status: "pending" | "approved" | "denied" | "expired"
}
