// TypesFromSerializers CacheKey 55881fff67e68c20ce5b29f80bfa3b3d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AbilityInvocation {
  id: string
  actionKey: string
  approvalId?: string
  completedAt?: string
  connection?: string
  createdAt: string
  decision: "allow" | "deny" | "pending"
  durationMs?: number
  errorSummary?: string
  outcome?: "success" | "error"
  principalLabel: string
  riskLevel?: string
  scope: Record<string, string[]>
  source?: string
  triggeredByLabel?: string
}
