// TypesFromSerializers CacheKey 8c860b718b9c6a8e62282512c3c4224d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AbilityApproval {
  id: string
  actionKey: string
  approverName?: string
  createdAt: string
  params: Record<string, unknown>
  principalLabel: string
  requiredRole: string
  resolvedAt?: string
  scope: Record<string, string[]>
  selfApprovable: boolean
  source?: string
  status: "pending" | "approved" | "denied" | "expired"
}
