// TypesFromSerializers CacheKey e20af8a55adeb4745d399dbf0d03fbae
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AbilityRole {
  id: string
  actionIds: string[]
  agentCount: number
  builtIn: boolean
  deleteBlockedReason?: string
  description?: string
  editBlockedReason?: string
  grantCount: number
  keyCount: number
  name: string
  pack?: string
  peopleCount: number
  slug: string
}
