// TypesFromSerializers CacheKey 56b87687eee5856ab8673ad497276550
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AbilityActionOption {
  id: string
  approvalExempt: boolean
  description?: string
  group: string
  key: string
  kind: string
  reversible: boolean
  riskLevel: string
  title?: string
}
