// TypesFromSerializers CacheKey 7ef3cf3719bfa4861ef9db3d799f8521
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AbilityApproval {
  id: string
  actionKey: string
  approverName?: string
  approvers: { kind: string; id: string }[]
  connection?: string
  createdAt: string
  params: Record<string, unknown>
  principalLabel: string
  requiredRole: string
  resolvedAt?: string
  scope: Record<string, string[]>
  selfApprovable: boolean
  source?: string
  status: "pending" | "approved" | "denied" | "expired"
}
