// TypesFromSerializers CacheKey d740e0eff43d15428fd2315ad54bc5bb
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AbilityActionOption {
  id: string
  approvalExempt: boolean
  group: string
  key: string
  kind: string
  reversible: boolean
  riskLevel: string
}
