// TypesFromSerializers CacheKey 897a1b508d1b4a46972f20c0b6241dfa
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AbilityRole {
  id: string
  actionIds: string[]
  builtIn: boolean
  deleteBlockedReason?: string
  description?: string
  editBlockedReason?: string
  grantCount: number
  name: string
  pack?: string
  slug: string
}
