// TypesFromSerializers CacheKey b75b8bd9b2ff60b04569f24578acacbd
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AbilityActionOption {
  id: string
  group: string
  key: string
  kind: string
  reversible: boolean
  riskLevel: string
}
