// TypesFromSerializers CacheKey 99b06ea3e2a45dcfd83ef3d47d61369c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AbilityInvocation {
  id: string
  actionKey: string
  approvalId?: string
  completedAt?: string
  createdAt: string
  decision: "allow" | "deny" | "pending"
  durationMs?: number
  errorSummary?: string
  outcome?: "success" | "error"
  principalLabel: string
  riskLevel?: string
  scope: Record<string, string[]>
  triggeredByLabel?: string
}
