// TypesFromSerializers CacheKey a02354b8b876f6be0770230915bf0c4c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AbilityRole {
  id: string
  actionIds: string[]
  grantCount: number
  name: string
  slug: string
}
