// TypesFromSerializers CacheKey 943ae6b12b0a3cbc42fdf6a04125683f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface ActorCompact {
  name: string
}
