// TypesFromSerializers CacheKey 2952b54ba63745056a532e3a20cef90b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface ActorCompact {
  avatarUrl?: string
  initials: string
  kind: string
  name: string
}
