// TypesFromSerializers CacheKey 4e0e2fc29ad0a50cb25da2f6ed91d90b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface ActorCompact {
  avatarUrl?: string
  kind: "user" | "agent" | "api_key" | "system_agent"
  name: string
}
