// TypesFromSerializers CacheKey 52e3bd6c5aca9edd18cf6decdf1e9499
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AgentChatMemoryQuestion {
  id: string
  at: string
  confirmBlockedReason?: string
  decided?: string
  evidence: string
  learnedAt?: string
  memoryId?: string
  origin?: string
  rejectBlockedReason?: string
  remembered?: string
  trust?: string
}
