// TypesFromSerializers CacheKey 1fad8aa574be219cf0fde8dfcb54e1a8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AgentChatAttachment {
  id: string
  kind: string
  name: string
  size: string
  unreadReason: string | null
  url: string
}
