// TypesFromSerializers CacheKey 042bad5332b0e442e57837298220a2e2
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AgentChatOwnerAsk {
  id: string
  at: string
  headline: string
  ownerName: string
  status: "pending" | "unreachable" | "asked" | "agreed" | "declined" | "withdrawn"
}
