// TypesFromSerializers CacheKey f9e0bc1fd76d899bf61656950b1a3b06
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AgentChatWatchUpdate {
  id: string
  at: string
  kind: "started" | "milestone" | "part_failed" | "handed_back" | "slow" | "progress" | "ended"
  text: string
  title: string
  tone: "started" | "milestone" | "part_failed" | "handed_back" | "slow" | "progress" | "done" | "failed" | "timed_out" | "stopped"
  watchId: string
}
