// TypesFromSerializers CacheKey 6e476c2830e8e2e7628e773b866b2aa0
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type AgentChatAttachment from './AgentChatAttachment'

export default interface AgentChatMessage {
  id: string
  attachments: AgentChatAttachment[]
  body: string
  createdAt: string
  role: string
  tools: { key: string; title: string; headline: string; asked: [string, string][]; status: string; kind: string; seconds: number; card: { kind: string; category: string | null } | null; outcome: { kind: string; said: string | null; lines: string[]; total: number; size: number; link: { provider: string; url: string } | null } | null; progress: { startedAt: string; live: boolean; total: number; lines: { text: string; at: string | null; result: string | null }[]; changed: string[]; tests: { command: string; passed: boolean }[]; files: { path: string; added: number | null; removed: number | null }[]; finishedAt: string | null; outcome: string | null; pullRequest: string | null; reason: string | null } | null }[]
}
