// TypesFromSerializers CacheKey 253ac8c1f6d0ac116e1e21a1a09a7079
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AgentChatPackRefusal {
  id: string
  askBlockedReason?: string
  askedLine?: string
  at: string
  body: string
  headline: string
}
