// TypesFromSerializers CacheKey 8b5348535360e3c5f041eb145eb4c298
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AgentChatWaitingMessage {
  id: string
  body: string
}
