// TypesFromSerializers CacheKey efac8abef312b1760395b6d346793392
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AgentChatHeldCall {
  id: string
  askAgainBlockedReason?: string
  asked: string[][]
  at: string
  callName: string
  change?: "unchanged" | "changed" | "already_done" | "gone" | "unknown"
  checkedAt?: string
  decidedBy?: string
  dismissBlockedReason?: string
  expiresAt?: string
  headline: string
  offers: string[]
  result?: string
  runBlockedReason?: string
  state?: string
  status: "waiting" | "checking" | "ready" | "running" | "ran" | "failed" | "dismissed" | "expired" | "denied" | "asked_again"
  target?: string
  warning?: string
}
