// TypesFromSerializers CacheKey ac8dda16ac2c40206a8281989be74445
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AgentChatWatch {
  id: string
  at: string
  basis?: string
  expiresAt: string
  headline: string
  outcome?: string
  purpose?: string
  status: "active" | "succeeded" | "failed" | "timed_out" | "stopped"
  steps: { id: string; label: string; status: string; state: string | null }[]
  stopBlockedReason?: string
  title: string
}
