// TypesFromSerializers CacheKey 15aabe186f4e2704beb103c46070e471
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AgentChatAttachmentRules {
  accept: string
  accepted: string
  imagesUnread: string | null
  maxBytes: number
  maxFiles: number
  maxSize: string
  tooMany: string
}
