// TypesFromSerializers CacheKey b22369109b02eeec645e954e29401cfa
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AgentChatWatch {
  id: string
  at: string
  basis?: string
  expiresAt: string
  headline: string
  outcome?: string
  purpose?: string
  reads: string
  status: "active" | "succeeded" | "failed" | "timed_out" | "stopped"
  steps: { id: string; label: string; status: "waiting" | "running" | "repairing" | "succeeded" | "failed" | "unfollowable"; state: string | null; url: string | null }[]
  stopBlockedReason?: string
  title: string
}
