// TypesFromSerializers CacheKey c218674dfb0c3c09a3916e5e302c58ff
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AgentChatConfirmation {
  asked: string[][]
  intent?: string
  question: string
  toolCallId: string
}
