// TypesFromSerializers CacheKey 40282b822773981ba8d043de445399f6
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type AgentChatAttachment from './AgentChatAttachment'

export default interface AgentChatWaitingMessage {
  id: string
  attachments: AgentChatAttachment[]
  body: string
}
