// TypesFromSerializers CacheKey 6afff1560cbe4e4f2a07332a6f779338
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AgentChatPlan {
  id: string
  at: string
  goal: string
  heading: string
  links: string[]
  nextStep?: string
  offers: { action: "schedule" | "cancel" | "retry" | "undo"; blockedReason: string | null }[]
  outcome?: string
  progress: string
  status: "proposed" | "scheduled" | "active" | "completed" | "stopped" | "cancelled"
  steps: { id: string; position: number; kind: "read" | "change" | "check"; description: string; place: string | null; status: "not_started" | "running" | "done" | "failed" | "skipped"; note: string | null; tool: string | null; verdict: "held" | "not_held" | "could_not_check" | null; undo: string | null; links: string[] }[]
  stopReason?: string
  undoes?: string
}
