// TypesFromSerializers CacheKey 3c917c0cd7a00d81382025ad3f075e75
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AgentChatWatchUpdate {
  id: string
  at: string
  kind: "started" | "milestone" | "part_failed" | "handed_back" | "repaired" | "corrected" | "ceiling" | "slow" | "progress" | "ended"
  name: string
  text: string
  title: string
  tone: "started" | "milestone" | "part_failed" | "handed_back" | "repaired" | "corrected" | "ceiling" | "slow" | "progress" | "done" | "failed" | "timed_out" | "stopped"
  watchId: string
}
