// TypesFromSerializers CacheKey 23d7d6a188d032c22976708fe5724ec0
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AgentChat {
  id: string
  archived: boolean
  pinned: boolean
  preview: string
  title: string
  updatedAt: string
}
