// TypesFromSerializers CacheKey df8b38d958bc9c93ac0dcb5319920cc7
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AgentChatPullRequestNotice {
  id: string
  at: string
  fixBlockedReason?: string
  fixedBy?: string
  headline: string
  offer: string
  reason: string
  status: "offered" | "fixing" | "cleared" | "replaced" | "ended"
  url?: string
}
