// TypesFromSerializers CacheKey 680200c04a5549df4e45c066b2c626b4
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AgentChatIncident {
  id: string
  identifier: string
  name: string
}
