// TypesFromSerializers CacheKey a4330d8093d02ba510dd657c18d10592
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AgentChatWatch {
  id: string
  at: string
  basis?: string
  expiresAt: string
  headline: string
  outcome?: string
  purpose?: string
  status: "active" | "succeeded" | "failed" | "timed_out" | "stopped"
  steps: { id: string; label: string; status: "waiting" | "running" | "succeeded" | "failed" | "unfollowable"; state: string | null }[]
  stopBlockedReason?: string
  title: string
}
