// TypesFromSerializers CacheKey dcb59a9bf39ba754dc3ec7cb1d8dd96c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AgentChatSecretEntry {
  id: string
  at: string
  blockedReason?: string
  body: string
  headline: string
  kind: string
  open: boolean
  statusLine?: string
}
