// TypesFromSerializers CacheKey 087948a37f023a8dcd207195f02682b5
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AgentChatConfirmation {
  asked: string[][]
  intent?: string
  question: string
  tool: string
  toolCallId: string
}
