// TypesFromSerializers CacheKey 6f51ebd55aec72249ca6b838c3c010b9
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AgentChatConfirmation {
  asked: string[][]
  question: string
  toolCallId: string
}
