// TypesFromSerializers CacheKey 26095ee9c9acb98ac22088c05071afd8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Agent {
  id: string
  description?: string
  enabled: boolean
  grantCount: number
  lastUsedAt?: string
  name: string
  slug: string
  tokens: { id: string; prefix: string; createdAt: string; lastUsedAt: string | null }[]
}
