// TypesFromSerializers CacheKey 771ec3789fb37c7039216729e7393a3a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type AgentChatAttachment from './AgentChatAttachment'

export default interface AgentChatMessage {
  id: string
  attachments: AgentChatAttachment[]
  body: string
  createdAt: string
  role: string
  tools: { key: string; title: string; headline: string; asked: [string, string][]; status: string; kind: string; seconds: number; card: { kind: string; category: string | null } | null }[]
}
