// TypesFromSerializers CacheKey a7dc91a1989adc3edc9d797f1e326b20
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AgentChat {
  id: string
  title: string
}
