// TypesFromSerializers CacheKey 0cb9c595179db2bfe0263651aa5645c9
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AgentChatDataRepair {
  id: string
  at: string
  checkError?: string
  copyKeptUntil?: string
  kind: "read" | "update" | "delete" | "insert" | "schema"
  rows: string
  wrongAfter?: number
  wrongBefore?: number
}
