// TypesFromSerializers CacheKey ad1aab337d35f22b3ff10efae584e1af
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AgentChatHelper {
  id: string
  brief: string
  endedBecause?: string
  finishedAt?: string
  report?: string
  startedAt: string
  status: "running" | "reported" | "failed" | "stopped"
  steps: { key: string; title: string; headline: string; asked: [string, string][]; status: string; outcome: { kind: string; said: string | null; lines: string[]; total: number; size: number; link: { provider: string; url: string } | null } | null }[]
  title: string
  toolCallId: string
}
