// TypesFromSerializers CacheKey adb43837a966cb87c508c6119bb1eb5b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AgentChatWatchUpdate {
  id: string
  at: string
  kind: "started" | "milestone" | "slow" | "ended"
  text: string
  title: string
  tone: "started" | "milestone" | "slow" | "done" | "failed" | "timed_out" | "stopped"
  watchId: string
}
