// TypesFromSerializers CacheKey 51abc4a4a275004f1a5743f6545cdc4a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AgentChat {
  id: string
  archived: boolean
  busy: boolean
  lastActiveAt: string
  pinned: boolean
  pinnedAt: string | null
  preview: string
  title: string
}
