// TypesFromSerializers CacheKey a14188b337d9eebc633d602db5d41994
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AgentChatMitigation {
  id: string
  at: string
  expiresAt?: string
  extendBlockedReason?: string
  keepBlockedReason?: string
  label: string
  outcome?: string
  status: "proposed" | "active" | "kept" | "undoing" | "undone" | "undo_failed" | "undo_held" | "due_by_hand" | "cancelled" | "with_plan"
  title: string
  undoBlockedReason?: string
  undoNote?: string
  undoState: "none" | "writing" | "ready" | "by_hand"
}
