// TypesFromSerializers CacheKey 2d2f4ed0cae5ef99f11ca7e27f69ad75
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AgentChatMessage {
  id: string
  body: string
  role: string
  tools: { key: string; title: string; headline: string; asked: [string, string][]; status: string; kind: string; seconds: number; card: { kind: string; category: string | null } | null }[]
}
