// TypesFromSerializers CacheKey b37f76fe7cc05e33ff025ff73198df6d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AiProviderOption {
  chatModels: string[]
  codeFixes: boolean
  fastModel?: string
  fields: { key: string; label: string; secret: boolean; required: boolean }[]
  mainModel?: string
  name: string
  slug: string
}
