// TypesFromSerializers CacheKey c63a711fae6731150e01a1d624471f17
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type PolicyRule from './PolicyRule'

export default interface AlertRoutingPolicy {
  id: string
  enabled: boolean
  rules: PolicyRule[]
}
