// TypesFromSerializers CacheKey c4a2f781f36d5fbe1798cf263eb4817c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type PolicyRule from './PolicyRule'

export default interface AlertRoutingPolicy {
  id: string
  contentMatchFields: string[]
  enabled: boolean
  groupingWindowMinutes: number
  rules: PolicyRule[]
}
