// TypesFromSerializers CacheKey d1410ba3954bead1c36fee8c051a006f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AlertSettings {
  id: string
  eventCount: number
  incidentId?: string
  incidentIdentifier?: string
  lastSeenAt: string
  receivedAt: string
  routingState: string
  sourceId: string
  sourceName: string
  status: string
  title: string
}
