// TypesFromSerializers CacheKey 8d075b8c20d136ca1d3cc5dd2bf5f3e6
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AlertSourceSettings {
  id: string
  createdAt: string
  enabled: boolean
  fieldMap: Record<string, string>
  fingerprintFields: string[]
  flapWindowMinutes: number
  ingestPath: string
  itemsPath?: string
  lastReceivedAt?: string
  lastRejectedAt?: string
  lastRejectionReason?: string
  name: string
  provider: string
  severityMap: Record<string, string>
}
