// TypesFromSerializers CacheKey a50c3d0d92cf3ebd59a056b9fd3aeff1
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AlertSourceSettings {
  id: string
  createdAt: string
  enabled: boolean
  ingestPath: string
  lastReceivedAt?: string
  lastRejectedAt?: string
  lastRejectionReason?: string
  name: string
  provider: string
  severityMap: Record<string, string>
}
