// TypesFromSerializers CacheKey a3a8194b8980a83f496668eb1d7b1cb4
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AlertSourceSettings {
  id: string
  createdAt: string
  enabled: boolean
  ingestPath: string
  name: string
  provider: string
  secretToken: string
  severityMap: Record<string, string>
}
