// TypesFromSerializers CacheKey 41359675f939a2306aec597bf4bf354a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AlertSettings {
  id: string
  eventCount: number
  incidentId?: string
  incidentIdentifier?: string
  lastSeenAt: string
  matchedRuleId?: string
  matchedRulePriority?: number
  matchedRuleSourceId?: string
  receivedAt: string
  routingState: string
  sourceId: string
  sourceName: string
  status: string
  title: string
}
