// TypesFromSerializers CacheKey 89b4f9dac1703a18e6c6ca6b809113e5
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface ApiKey {
  id: string
  active: boolean
  createdAt: string
  createdBy: string
  expiresAt?: string
  lastUsedAt?: string
  name: string
  permissions: Record<string, string[]>
  tokenPrefix: string
}
