// TypesFromSerializers CacheKey 7196e28f4af893ff95ed0712d9dfb0bd
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface ApiKey {
  id: string
  active: boolean
  createdAt: string
  createdBy: string
  expiresAt?: string
  kind: string
  lastUsedAt?: string
  name: string
  ownerName?: string
  permissions: Record<string, string[]>
  tokenPrefix: string
}
