// TypesFromSerializers CacheKey d393d88cb4a7f4bf0e31ce3a31942c2f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface ApprovalRule {
  id: string
  actionKeys: string[]
  approverIds: string[]
  enabled: boolean
  environments: string[]
  notify: "channel" | "dm" | "both"
  priority: number
  riskLevels: string[]
  role: string
  selfApproval: boolean
}
