// TypesFromSerializers CacheKey 77c57b2865f809db6330c81225b086d0
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface ApprovalRule {
  id: string
  actionKeys: string[]
  agentsMayApprove: boolean
  approvers: { kind: string; id: string }[]
  enabled: boolean
  environments: string[]
  notify: "channel" | "dm" | "both"
  onCall: boolean
  priority: number
  riskLevels: string[]
  role: string
  selfApproval: boolean
}
