// TypesFromSerializers CacheKey f34021cbd7db821d76f692d2f43824dd
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface ApprovalRule {
  id: string
  actionKeys: string[]
  agentsMayApprove: boolean
  approvers: { kind: string; id: string }[]
  enabled: boolean
  environments: string[]
  notify: "channel" | "dm" | "both"
  priority: number
  riskLevels: string[]
  role: string
  selfApproval: boolean
}
