// TypesFromSerializers CacheKey 1f8e9f90dbd63d9c47289dd1ff4ba13f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface CatalogEntry {
  id: string
  attributes: Record<string, unknown>
  createdAt: string
  externalId?: string
  name: string
  slug: string
  source?: string
  typeId: string
  updatedAt: string
}
