// TypesFromSerializers CacheKey 4bdb770460d3714a52c7444450329bda
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface CatalogTypeOption {
  id: string
  color?: string
  icon?: string
  name: string
  slug: string
}
