// TypesFromSerializers CacheKey 0dad615d44cc5b495597fcfe7df1b6a8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface CatalogAttributeDefinition {
  id: string
  attributeType: string
  key: string
  name: string
  options?: string[]
  position: number
  referenceTypeId?: string
  required: boolean
}
