// TypesFromSerializers CacheKey ad12c85b93612c608f4f13e6579de6f1
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface CatalogAttributeDefinition {
  id: string
  attributeType: "text" | "number" | "boolean" | "select" | "list" | "reference" | "slack_channel" | "workspace_member" | "workspace_members"
  name: string
  options?: string[]
  position: number
  referenceTypeId?: string
  required: boolean
  role?: "members" | "manager" | "notification_channel" | "repository"
  slug: string
}
