// TypesFromSerializers CacheKey 11fac3e33d6490559088e128ce0a2efc
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CatalogAttributeDefinition from './CatalogAttributeDefinition'

export default interface CatalogType {
  id: string
  attributeDefinitions: CatalogAttributeDefinition[]
  color?: string
  description?: string
  entryCount: number
  icon?: string
  kind: string
  name: string
  position: number
  slug: string
  systemKey?: string
}
