// TypesFromSerializers CacheKey 04d6e84c5e21f90cb620101937430697
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface CatalogAttributeDefinition {
  id: string
  attributeType: "text" | "number" | "boolean" | "select" | "list" | "reference" | "slack_channel" | "workspace_member" | "workspace_members"
  name: string
  options?: string[]
  position: number
  referenceTypeId?: string
  required: boolean
  role?: "members" | "manager" | "notification_channel"
  slug: string
}
