// TypesFromSerializers CacheKey e9c844bdd7c204a2ae1f466e2a358b29
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CatalogAttributeDefinition from './CatalogAttributeDefinition'

export default interface CatalogType {
  id: string
  attributeDefinitions: CatalogAttributeDefinition[]
  color?: string
  deletionBlockedReason?: string
  description?: string
  entryCount: number
  icon?: string
  kind: string
  name: string
  position: number
  slug: string
  systemKey?: string
}
