// TypesFromSerializers CacheKey d207317ca0ce65f8e2554e20c04a0f24
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface ChatCompaction {
  at: string
  key: string
  title: string
}
