// TypesFromSerializers CacheKey 6aa0bee16214b7516b137b82468296c6
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface ChatChart {
  id: string
  rangeEnd: string
  rangeStart: string
  series: { label: string; points: [string, number][] }[]
  sourceUrl?: string
  stepPosition?: number
  title: string
  toolCallId: string
  unit: string
}
