// TypesFromSerializers CacheKey 2a6d8430a1b496debabd7c6228de7b9c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ChatModelOption from './ChatModelOption'

export default interface ChatModelMenu {
  models: ChatModelOption[]
  selected: string
}
