// TypesFromSerializers CacheKey d5c59d4f16a0d085f2749385bb46e6ce
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface ChatModelSwitch {
  at: string
  key: string
  title: string
}
