// TypesFromSerializers CacheKey 0af511791c90cd40adc6c7c567673f57
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface ChatModelOption {
  id: string
  default: boolean
  imagesUnread: string | null
  label: string
  note: string
}
