// TypesFromSerializers CacheKey 8c31a8804400332dab636148941b5f05
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ChatMemoryState from '../ChatMemoryState'

export default interface ChatMemory {
  id: string
  about?: string
  aboutRemoved: boolean
  addedBy?: string
  confirmBlockedReason?: string
  confirmedAt?: string
  confirmedBy?: string
  createdAt: string
  decidedByPostmortem: boolean
  deleteConsequence: string
  inUse: boolean
  lastUsedAt?: string
  reason?: string
  rejectBlockedReason?: string
  rejectedBy?: string
  sourceIncidentId?: string
  sourceLabel: string
  state: ChatMemoryState
  subject?: string
  text: string
  useCount: number
}
