// TypesFromSerializers CacheKey 89897e319ae49626bec3025002c2a64d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ChatMemoryState from '../ChatMemoryState'

export default interface ChatMemory {
  id: string
  about?: string
  addedBy?: string
  confirmedAt?: string
  confirmedBy?: string
  createdAt: string
  lastUsedAt?: string
  reason?: string
  rejectedBy?: string
  sourceIncidentId?: string
  sourceLabel: string
  state: ChatMemoryState
  subject?: string
  text: string
  useCount: number
}
