// TypesFromSerializers CacheKey 8197c38884f2180e89d56f53013ae5a8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface ChatInstruction {
  id: string
  addedBy?: string
  history: string[][]
  label: string
  scope?: string
  text: string
  updatedAt: string
}
