// TypesFromSerializers CacheKey c5362d109491a0079d570927d5ebda4e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ChatMemoryState from '../ChatMemoryState'

export default interface ChatMemory {
  id: string
  about?: string
  addedBy?: string
  confirmBlockedReason?: string
  confirmedAt?: string
  confirmedBy?: string
  createdAt: string
  inUse: boolean
  lastUsedAt?: string
  reason?: string
  rejectBlockedReason?: string
  rejectedBy?: string
  sourceIncidentId?: string
  sourceLabel: string
  state: ChatMemoryState
  subject?: string
  text: string
  useCount: number
}
