// TypesFromSerializers CacheKey 4c2d3735fa73d948f67b19f75bebf526
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface CurrentWorkspace {
  id: string
  avatarUrl?: string
  disconnected: boolean
  name: string
  platform: string
}
