// TypesFromSerializers CacheKey 02808405c6060643433bf7127affc205
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface CurrentUser {
  id: string
  avatarUrl?: string
  email: string
  name: string
}
