// TypesFromSerializers CacheKey ef1c0f835dd381b40c20afccea415d28
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface CurrentWorkspace {
  id: string
  avatarUrl?: string
  chatConnected: boolean
  disconnected: boolean
  incidentsBlockedReason?: string
  name: string
  platform?: string
}
