// TypesFromSerializers CacheKey 7ac3d6bc217d48b5a417ce7dcb9ccad3
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface CurrentWorkspace {
  id: string
  avatarUrl?: string
  name: string
  platform: string
}
