// TypesFromSerializers CacheKey cda0d6477ec1853790e5cc2a3f866f60
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface EnvironmentOption {
  id: string
  name: string
  slug: string
}
