// TypesFromSerializers CacheKey 743bd3be6441310df5e410899b9333f0
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface HalonPerformanceWeek {
  confirmed: number
  notRated: number
  partial: number
  startsOn: string
  wrong: number
}
