// TypesFromSerializers CacheKey 70f10c911391f46808de3997dca0c5d1
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface HalonMistake {
  id: string
  cause?: string
  incidentId?: string
  investigationId: string
  label: string
  lessons: { id: string; text: string; confirmed: boolean }[]
  markedAt?: string
  summary: string
}
