// TypesFromSerializers CacheKey 6f9c98db443fd12633a9d82dfcebeb5a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type HalonMistake from './HalonMistake'
import type HalonPerformanceWeek from './HalonPerformanceWeek'

export default interface HalonPerformance {
  answered: number
  confirmed: number
  days: number
  ended: number
  fixesApplied: number
  fixesCancelled: number
  fixesProposed: number
  fixesUndone: number
  medianSeconds?: number
  mistakes: HalonMistake[]
  notRated: number
  partial: number
  rated: number
  runs: number
  weeks: HalonPerformanceWeek[]
  wrong: number
}
