// TypesFromSerializers CacheKey 94bc83ee0c367a35ff95aff3c8aa94a0
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface HandbookSource {
  id: string
  connection?: string
  kind: 'repository' | 'document'
  label: string
  pageCount: number
  syncError?: string
  syncedAt?: string
  url?: string
}
