// TypesFromSerializers CacheKey f22d2a1a95a5af2462ab2307c936ae91
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface HandbookFreezeWindow {
  active: boolean
  endDay?: number
  endTime?: string
  endsAt?: string
  liftedBy?: string
  name: string
  repeat: 'weekly' | 'once'
  sentence: string
  startDay?: number
  startTime?: string
  startsAt?: string
  timeZone: string
}
