// TypesFromSerializers CacheKey afa2847e349e3ff864e542072f0c9528
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface HandbookSuggestion {
  example: string
  freezes: boolean
  hint: string
  takesRole: boolean
  title: string
}
