// TypesFromSerializers CacheKey 375ecf0ac1fd4167c56d44cd000f3bee
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface HandbookProposal {
  id: string
  acceptBlockedReason?: string
  at: string
  currentWording?: string
  decided?: string
  dismissBlockedReason?: string
  evidence: string
  newPage: boolean
  origin: string
  pageTitle: string
  text: string
}
