// TypesFromSerializers CacheKey 49b62039851c1a916b337386616b2a33
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface HandbookRole {
  id: string
  description?: string
  name: string
}
