// TypesFromSerializers CacheKey 57b0d31617ab0a3f7b341d397b9672b5
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface HandbookImporter {
  id: string
  kind: 'repository' | 'document'
  name: string
  repositories: string[]
}
