// TypesFromSerializers CacheKey 92eca02fabc935d219ba8c02ecae6bb7
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type HandbookFreezeWindow from './HandbookFreezeWindow'

export default interface HandbookPage {
  id: string
  addedBy?: string
  anchors: string[][]
  deleteBlockedReason?: string
  directingRoleId?: string
  directingRoleName?: string
  editBlockedReason?: string
  freezeWindows: HandbookFreezeWindow[]
  halonReads: 'whole' | 'searched'
  history: string[][]
  kind: 'written' | 'directing' | 'synced'
  roleSetAside: boolean
  sourceId?: string
  sourceLabel?: string
  sourceUrl?: string
  text: string
  title: string
  updatedAt?: string
  wordingId?: string
}
