// TypesFromSerializers CacheKey de0e431b3a5680bb2e1624e638de9549
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface IncidentAction {
  id: string
  actionType: "action" | "followup"
  assignee?: string
  assigneeAvatarUrl?: string
  createdBy: string
  description: string
  status: "open" | "in_progress" | "done"
}
