// TypesFromSerializers CacheKey 6998392ec776026317b426e5d6092d69
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type IncidentFormFieldSettings from '../IncidentFormFieldSettings'

export default interface IncidentFormSettings {
  id: string
  conditionSources: { id: string; name: string; options: { id: string; name: string }[] }[]
  description?: string
  fields: IncidentFormFieldSettings[]
  isDefault: boolean
  lifecycleEvent: string
  name: string
  position: number
  slug: string
}
