// TypesFromSerializers CacheKey 057da482d8b5863f0217aa6bdd9ea291
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type SeverityCompact from './SeverityCompact'
import type StatusCompact from './StatusCompact'

export default interface IncidentListItem {
  id: string
  declaredAt: string
  identifier: string
  lead?: string
  name: string
  resolvedAt?: string
  severity: SeverityCompact
  status: StatusCompact
}
