// TypesFromSerializers CacheKey 27ef75413576809ecee131c8191d4828
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type IncidentConditionSettings from '../IncidentConditionSettings'

export default interface IncidentFormFieldSettings {
  id: string
  catalogTypeId?: string
  catalogTypeName?: string
  conditions?: IncidentConditionSettings[]
  description?: string
  fieldSourceKind: string
  fieldType: string
  incidentFieldDefinitionId?: string
  isDefault: boolean
  key: string
  lockedRequired: boolean
  name: string
  optionSource?: string
  options?: { id: string; name: string }[]
  position: number
  requiredMode: string
  systemFieldKey?: string
  visibilityMode: string
}
