// TypesFromSerializers CacheKey db50cd1055439ddb87b40ca6f0cfd446
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface IncidentTypeSettings {
  id: string
  color?: string
  deletionBlockedReason?: string
  description?: string
  disableBlockedReason?: string
  enabled: boolean
  name: string
  position: number
  slug: string
}
