// TypesFromSerializers CacheKey 101381c9b8f4bdca00dda7376fe12760
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface IncidentTypeCompact {
  name: string
}
