// TypesFromSerializers CacheKey b5327e9f8efb37235ccf6cd06f6d0b61
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type SeverityCompact from './SeverityCompact'
import type StatusCompact from './StatusCompact'

export default interface IncidentListItem {
  id: string
  declaredAt: string
  declaredBy?: string
  identifier: string
  lead?: string
  name: string
  resolvedAt?: string
  severity: SeverityCompact
  status: StatusCompact
}
