// TypesFromSerializers CacheKey 1617a4c29294b94e6871c1f5a7cf7d26
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ActorCompact from '../ActorCompact'
import type IncidentLead from '../IncidentLead'
import type IncidentTypeCompact from '../IncidentTypeCompact'
import type SeverityDetail from './SeverityDetail'
import type StatusDetail from './StatusDetail'

export default interface IncidentDetail {
  id: string
  channelName?: string
  customFields?: Record<string, unknown>
  declaredAt: string
  declaredBy?: ActorCompact
  detectedAt?: string
  identifier: string
  isPrivate: boolean
  lead?: IncidentLead
  name: string
  resolvedAt?: string
  severity: SeverityDetail
  source: string
  status: StatusDetail
  summary: string
  type?: IncidentTypeCompact
}
