// TypesFromSerializers CacheKey 97389f6dc215efaa07820491581fe2c8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type IncidentFieldOption from './IncidentFieldOption'

export default interface IncidentFieldDefinitionSettings {
  id: string
  catalogTypeId?: string
  catalogTypeName?: string
  deletionBlockedReason?: string
  description?: string
  enabled: boolean
  fieldType: string
  name: string
  optionSource: string
  options: IncidentFieldOption[]
  position: number
  shapeChangeBlockedReason?: string
  slug: string
  usageCount: number
}
