// TypesFromSerializers CacheKey 054b8d0c5f228d9298228256f5dfd26e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface IncidentTypeSettings {
  id: string
  color?: string
  description?: string
  incidentCount: number
  isDefault: boolean
  name: string
  position: number
  slug: string
}
