// TypesFromSerializers CacheKey 77c7061dbc1f200411529406c2b96f94
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ActorCompact from './ActorCompact'

export default interface IncidentSubscriber {
  id: string
  member: ActorCompact
}
