// TypesFromSerializers CacheKey 40a26ab0683dfd8ff14b04ddda2a576e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ActorCompact from './ActorCompact'

export default interface IncidentRoleAssignment {
  id: string
  member?: ActorCompact
  memberId?: string
  name: string
  slug: string
}
