// TypesFromSerializers CacheKey 32ccf4cb9a53d5cad3e99c3c62e10f5a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface IncidentSeveritySettings {
  id: string
  color: string
  deletable: boolean
  description?: string
  enabled: boolean
  isDefault: boolean
  name: string
  position: number
  rank: number
  slug: string
}
