// TypesFromSerializers CacheKey e070de46eea43c7ae60b4418b25da1bd
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface IncidentFieldOption {
  id: string
  deletionBlockedReason?: string
  enabled: boolean
  label: string
  position: number
  usageCount: number
}
