// TypesFromSerializers CacheKey 6b71e2113bed9eb9c8477f1675441963
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface IncidentStatusSettings {
  id: string
  color: string
  defaultBlockedReason?: string
  deletionBlockedReason?: string
  description?: string
  disableBlockedReason?: string
  enabled: boolean
  incidentCount: number
  isDefault: boolean
  name: string
  position: number
  slug: string
}
