// TypesFromSerializers CacheKey 25d14e33df4d68ce382d664faf869929
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface IncidentLead {
  initials: string
  name: string
}
