// TypesFromSerializers CacheKey 4d343f8397c2be242e400a3d031a0c9b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface IncidentRunbook {
  id: string
  doneCount: number
  externalUrl?: string
  name: string
  runbookId: string
  slug: string
  steps: { id: string; title: string; instruction: string | null; assignee: string | null; done: boolean }[]
  stepsCount: number
  summary?: string
}
