// TypesFromSerializers CacheKey dc3e0aa23d80f4c35492bc71be609119
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type IncidentLead from '../IncidentLead'

export default interface IncidentRoleAssignment {
  id: string
  member: IncidentLead
  name: string
  slug: string
}
