// TypesFromSerializers CacheKey 83066a2ae1d3758da259d107c9658808
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface IncidentStatusSettings {
  id: string
  color: string
  deletable: boolean
  description?: string
  enabled: boolean
  isDefault: boolean
  name: string
  position: number
  slug: string
}
