// TypesFromSerializers CacheKey d2f644328e23b7e99d8e48abd7a82601
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface IncidentFieldDefinitionSettings {
  id: string
  catalogTypeId?: string
  catalogTypeName?: string
  description?: string
  fieldType: string
  key: string
  name: string
  optionSource: string
  options: string[]
  position: number
  usageCount: number
}
