// TypesFromSerializers CacheKey d9c6aafeff78dcb08d7916307ca6931f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ActorCompact from '../ActorCompact'

export default interface IncidentRoleAssignment {
  id: string
  member: ActorCompact
  name: string
  slug: string
}
