// TypesFromSerializers CacheKey 36c03cbd13b4cb3653ab3052dc6aeabb
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type IncidentConditionSettings from '../IncidentConditionSettings'

export default interface IncidentFormFieldSettings {
  id: string
  catalogTypeId?: string
  catalogTypeName?: string
  conditions?: IncidentConditionSettings[]
  description?: string
  fieldSourceKind: string
  fieldType: string
  incidentFieldDefinitionId?: string
  isDefault: boolean
  key: string
  lockedRequired: boolean
  name: string
  optionSource?: string
  options?: string[]
  position: number
  requiredMode: string
  systemFieldKey?: string
  visibilityMode: string
}
