// TypesFromSerializers CacheKey 2eeb1003821f71be9e9e32e60d512a9b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type SeverityCompact from './SeverityCompact'
import type StatusCompact from './StatusCompact'

export default interface IncidentListItem {
  id: string
  declaredAt: string
  declaredBy?: string
  identifier: string
  isTest: boolean
  lead?: string
  name: string
  resolvedAt?: string
  severity: SeverityCompact
  status: StatusCompact
}
