// TypesFromSerializers CacheKey 7507866afc968fa4348de6d53e24324a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface IncidentRunbook {
  id: string
  claimedCount: number
  doneCount: number
  externalUrl?: string
  name: string
  slug: string
  stepsCount: number
  summary?: string
}
