// TypesFromSerializers CacheKey d011d3662f38efc387fa6e2c6bb52789
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface IncidentAlert {
  id: string
  eventCount: number
  lastSeenAt: string
  sourceName: string
  status: string
  title: string
}
