// TypesFromSerializers CacheKey b2b0e956a4aa99dbb6a3ea3f0140e2ca
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type IncidentFieldOption from './IncidentFieldOption'

export default interface IncidentFieldDefinitionSettings {
  id: string
  catalogTypeId?: string
  catalogTypeName?: string
  deletionBlockedReason?: string
  description?: string
  enabled: boolean
  fieldType: string
  key: string
  name: string
  optionSource: string
  options: IncidentFieldOption[]
  position: number
  shapeChangeBlockedReason?: string
  usageCount: number
}
