// TypesFromSerializers CacheKey 647fa8e82843e97b9fd4679217b55e58
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface IncidentStatusSettings {
  id: string
  color: string
  defaultable: boolean
  deletable: boolean
  description?: string
  enabled: boolean
  incidentCount: number
  isDefault: boolean
  lastEnabledInStage: boolean
  name: string
  position: number
  slug: string
}
