// TypesFromSerializers CacheKey 1d650c26432c49cdc850bbcbd0715f9d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type IncidentFormFieldSettings from './IncidentFormFieldSettings'

export default interface IncidentFormSettings {
  id: string
  description?: string
  fieldCount: number
  fields: IncidentFormFieldSettings[]
  lifecycleEvent: string
  name: string
  position: number
  slug: string
}
