// TypesFromSerializers CacheKey d078361be5c4c6165b975ee5c85b2f6e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface IncidentRole {
  id: string
  deletable: boolean
  description?: string
  enabled: boolean
  name: string
  position: number
  slug: string
  system: boolean
}
