// TypesFromSerializers CacheKey 20187f30c0cad4094dda567055b43956
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ActorCompact from './ActorCompact'

export default interface IncidentAction {
  id: string
  actionType: "action" | "followup"
  assignee?: ActorCompact
  createdBy: ActorCompact
  description: string
  externalKey?: string
  externalUrl?: string
  status: "open" | "in_progress" | "done"
}
