// TypesFromSerializers CacheKey e46282161e766d6dea98f97a6994f7b0
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface IncidentLead {
  avatarUrl?: string
  initials: string
  name: string
}
