// TypesFromSerializers CacheKey 7052a74ac3017a22c4e536f861dee03a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type IncidentFormFieldSettings from '../IncidentFormFieldSettings'

export default interface IncidentFormSettings {
  id: string
  description?: string
  fieldCount: number
  fields: IncidentFormFieldSettings[]
  isDefault: boolean
  lifecycleEvent: string
  name: string
  position: number
  slug: string
}
