// TypesFromSerializers CacheKey 38562230bfd43a2b4b0e76503de43ef0
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ActorCompact from './ActorCompact'

export default interface IncidentAction {
  id: string
  actionType: "action" | "followup"
  assignee?: ActorCompact
  createdBy: ActorCompact
  description: string
  status: "open" | "in_progress" | "done"
}
