// TypesFromSerializers CacheKey 5a3f4e867c8935af87e865e1c5bac875
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface IncidentTypeSettings {
  id: string
  color?: string
  defaultBlockedReason?: string
  deletionBlockedReason?: string
  description?: string
  disableBlockedReason?: string
  enabled: boolean
  incidentCount: number
  isDefault: boolean
  name: string
  position: number
  slug: string
}
