// TypesFromSerializers CacheKey 13f7f9fbbe7cdf2e4abc6559bd945527
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface IncidentRunbook {
  id: string
  doneCount: number
  externalUrl?: string
  name: string
  runbookId: string
  slug: string
  stepsCount: number
  summary?: string
}
