// TypesFromSerializers CacheKey c334d5e9268346d02d6790c88360dd89
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface IncidentPromptField {
  choices?: { value: string; label: string }[]
  dispatches: boolean
  hint?: string
  input: "text" | "long_text" | "number" | "link" | "select" | "multi_select" | "person"
  key: string
  label: string
  placeholder?: string
  required: boolean
  value?: string | string[] | null
}
