// TypesFromSerializers CacheKey 155dded08ca800e40e5fc07ac31e21b4
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface IncidentRole {
  id: string
  deletionBlockedReason?: string
  description?: string
  disableBlockedReason?: string
  enabled: boolean
  incidentCount: number
  name: string
  position: number
  slug: string
  system: boolean
}
