// TypesFromSerializers CacheKey ea52d6f22a98b2458213ff452ef10423
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface IncidentSeveritySettings {
  id: string
  color: string
  defaultBlockedReason?: string
  deletionBlockedReason?: string
  description?: string
  disableBlockedReason?: string
  enabled: boolean
  incidentCount: number
  isDefault: boolean
  name: string
  position: number
  rank: number
  slug: string
}
