// TypesFromSerializers CacheKey df6463a52ac465e561e3f41c51ca6b3e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface IncidentSeveritySettings {
  id: string
  color: string
  deletable: boolean
  description?: string
  enabled: boolean
  incidentCount: number
  isDefault: boolean
  name: string
  position: number
  rank: number
  slug: string
}
