// TypesFromSerializers CacheKey 561edf6a0e8016dac9b2fabf9eb9f713
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type IncidentAlert from './IncidentAlert'
import type ActorCompact from './ActorCompact'
import type IncidentRoleAssignment from './IncidentRoleAssignment'
import type IncidentRunbook from './IncidentRunbook'
import type SeverityCompact from './SeverityCompact'
import type StatusCompact from './StatusCompact'
import type IncidentSubscriber from './IncidentSubscriber'
import type IncidentTypeCompact from './IncidentTypeCompact'

export default interface IncidentDetail {
  id: string
  actionBlockedReason?: string
  alerts: IncidentAlert[]
  changeBlockedReason?: string
  channelId?: string
  channelLabel: string
  channelName?: string
  customFields?: Record<string, unknown>
  declaredAt: string
  declaredBy?: ActorCompact
  detectedAt?: string
  escalationBlockedReason?: string
  followupBlockedReason?: string
  identifier: string
  inviteBlockedReason?: string
  isPrivate: boolean
  isTest: boolean
  lead?: ActorCompact
  leadId?: string
  name: string
  onboardingWalkthrough: boolean
  resolvedAt?: string
  roles: IncidentRoleAssignment[]
  runbooks: IncidentRunbook[]
  severity: SeverityCompact
  shoutoutBlockedReason?: string
  source: string
  status: StatusCompact
  subscribers: IncidentSubscriber[]
  summary: string
  type?: IncidentTypeCompact
}
