// TypesFromSerializers CacheKey 71d35ddd0d9f03aee33903ceb2fa3c5e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type IntegrationProvider from './IntegrationProvider'

export default interface IntegrationCardRow {
  action: "connect" | "reconnect" | "manage"
  actionLabel: string
  connections: { id: string; name: string }[]
  provider: IntegrationProvider
  state: "connected" | "needs_attention" | "turned_off" | "not_connected"
  stateLabel: string
}
