// TypesFromSerializers CacheKey efecc138c80606ec30759f245bacf2a0
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type IntegrationProvider from './IntegrationProvider'

export default interface IntegrationCardRow {
  connections: { id: string; name: string }[]
  provider: IntegrationProvider
  state: "connected" | "needs_attention" | "turned_off" | "not_connected"
}
