// TypesFromSerializers CacheKey 0ca65d487656165608bdb1db664d06c1
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Integration {
  id: string
  disabled: boolean
  environments: { id: string; environmentName: string | null; enabled: boolean; healthStatus: string; healthError: string | null }[]
  name: string
  provider: string
  slug: string
  tools: { id: string; name: string; description: string | null; actionKey: string; readOnly: boolean; enabled: boolean }[]
}
