// TypesFromSerializers CacheKey ede46b5b0152f558b5c3de0b645a3652
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type IntegrationCardRow from './IntegrationCardRow'

export default interface IntegrationCard {
  category: string
  name: string
  rows: IntegrationCardRow[]
  tagline: string
}
