// TypesFromSerializers CacheKey 1ccc20a480913e8a9d48ee56fb7b0995
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Integration {
  id: string
  disabled: boolean
  environments: { id: string; environmentId: string | null; environmentName: string | null; enabled: boolean; healthStatus: "unknown" | "healthy" | "failing"; healthError: string | null; settings: { label: string; value: string }[]; choices: { key: string; label: string; hint: string; value: string | null; options: { value: string; label: string }[] }[]; liveUpdates: { on: boolean; lastEventAt: string | null; reason: string | null; setup: { address: string | null; steps: string[]; secretSet: boolean } | null } | null }[]
  kind: "mcp" | "http" | "native"
  name: string
  provider: string
  slug: string
  tools: { id: string; name: string; description: string | null; actionKey: string; readOnly: boolean; enabled: boolean; available: boolean; toggleBlockedReason: string | null }[]
}
