// TypesFromSerializers CacheKey 62fc777abf31f4cbc1016196bba37b94
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface IntegrationProvider {
  category: string
  color: string
  connectWith?: "connection_url" | "api_token"
  credentialFields: { key: string; label: string; hint: string; placeholder: string; secret: boolean }[]
  description: string
  halon: string
  key: string
  kind: "mcp" | "http" | "native"
  mark: string
  name: string
  onMap: boolean
  serverUrl: string
}
