// TypesFromSerializers CacheKey 667850ac581f9e37d37a49c06bf00df6
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface IntegrationProvider {
  category: string
  color: string
  connectFields: { key: string; label: string; hint: string; placeholder: string; numeric: boolean; optional: boolean; address: boolean; allowed: string | null; options: { value: string; label: string }[]; multiple: boolean; default: string | null }[]
  connectWith?: "connection_url" | "api_token"
  credentialFields: { key: string; label: string; hint: string; placeholder: string; secret: boolean; optional: boolean; multiline: boolean }[]
  description: string
  halon: string
  key: string
  kind: "mcp" | "http" | "native"
  mark: string
  mcpAlternative: boolean
  name: string
  onMap: boolean
  regions: { key: string; label: string; serverUrl: string }[]
  serverUrl: string
}
