// TypesFromSerializers CacheKey bc6ca84fb6952301233024495de00d3a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Integration {
  id: string
  disabled: boolean
  environments: { id: string; environmentId: string | null; environmentName: string | null; enabled: boolean; healthStatus: "unknown" | "healthy" | "failing"; healthError: string | null }[]
  kind: "mcp" | "http" | "native"
  name: string
  provider: string
  slug: string
  tools: { id: string; name: string; description: string | null; actionKey: string; readOnly: boolean; enabled: boolean; available: boolean; toggleBlockedReason: string | null }[]
}
