// TypesFromSerializers CacheKey 99085918f4d8f40f3dec4aaa3335bc2b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface IntegrationProvider {
  category: string
  color: string
  description: string
  key: string
  kind: "mcp" | "http" | "native"
  mark: string
  name: string
  serverUrl: string
}
