// TypesFromSerializers CacheKey 71253c686c56576fcd990ccd72ff833a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type IntegrationProvider from './IntegrationProvider'

export default interface IntegrationCardRow {
  connections: string[]
  provider: IntegrationProvider
  state: "connected" | "needs_attention" | "turned_off" | "not_connected"
}
