// TypesFromSerializers CacheKey 151d5d742654f4514f6e474507f1fbf5
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface InvestigationNoteFile {
  id: string
  kind: string
  name: string
  size: string
  unreadReason: string | null
  url: string | null
}
