// TypesFromSerializers CacheKey 59b33e7339379e7e850a9694ce0cbdfe
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface InvestigationCard {
  id: string
  answer?: string
  incidentId?: string
  incidentIdentifier?: string
  question?: string
  status: string
  suggestsIncident: boolean
  toolCallId?: string
}
