// TypesFromSerializers CacheKey b6c1f6e87138a78d674b9ea33214cb5d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface InvestigationEvidence {
  id: string
  claim: string
  steps: number[]
}
