// TypesFromSerializers CacheKey c5d1b77017068c997a670e5a2630bba7
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ChatChart from './ChatChart'

export default interface InvestigationCard {
  id: string
  answer?: string
  charts: ChatChart[]
  durationSeconds?: number
  incidentId?: string
  incidentIdentifier?: string
  question?: string
  status: string
  steps: { position: number, label: string, status: string }[]
  stopBlockedReason?: string
  suggestsIncident: boolean
  toolCallId?: string
}
