// TypesFromSerializers CacheKey 0767d334d52154b222235e3125d7ba9f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type RemediationPlanStatus from '../RemediationPlanStatus'
import type InvestigationRemediationStep from './InvestigationRemediationStep'

export default interface InvestigationRemediationPlan {
  id: string
  appliable: boolean
  appliedAt?: string
  appliedBy?: string
  applyBlockedReason?: string
  cancelBlockedReason?: string
  cancelledAt?: string
  cancelledBy?: string
  isUndo: boolean
  moving: boolean
  status: RemediationPlanStatus
  steps: InvestigationRemediationStep[]
  summary: string
  undoBlockedReason?: string
  undoError?: string
  verify?: string
  writingUndo: boolean
}
