// TypesFromSerializers CacheKey ab7f8140b0ba70f3cee51a9cae9af13d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type RemediationPlanStatus from '../RemediationPlanStatus'
import type InvestigationRemediationStep from './InvestigationRemediationStep'
import type InvestigationRemediationPlan from './InvestigationRemediationPlan'

export default interface InvestigationFixPlan {
  id: string
  appliable: boolean
  appliedAt?: string
  appliedBy?: string
  applyBlockedReason?: string
  cancelBlockedReason?: string
  cancelledAt?: string
  cancelledBy?: string
  isUndo: boolean
  moving: boolean
  status: RemediationPlanStatus
  steps: InvestigationRemediationStep[]
  summary: string
  undo?: InvestigationRemediationPlan
  undoBlockedReason?: string
  undoError?: string
  verify?: string
  writingUndo: boolean
}
