// TypesFromSerializers CacheKey d8e1c46c12d345091b2e2270982c7b82
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ChatChart from './ChatChart'

export default interface InvestigationCard {
  id: string
  answer?: string
  charts: ChatChart[]
  durationSeconds?: number
  incidentId?: string
  incidentIdentifier?: string
  question?: string
  status: string
  steps: { position: number, label: string, status: string }[]
  suggestsIncident: boolean
  toolCallId?: string
}
