// TypesFromSerializers CacheKey 609d064e7884e51b78bd6adab62d1ba8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ActorCompact from './ActorCompact'
import type ChatChart from './ChatChart'
import type ChatCompaction from './ChatCompaction'
import type InvestigationFinding from './InvestigationFinding'
import type InvestigationHelper from './InvestigationHelper'
import type InvestigationHypothesis from './InvestigationHypothesis'
import type InvestigationNote from './InvestigationNote'
import type InvestigationStep from './InvestigationStep'

export default interface InvestigationDetail {
  id: string
  asker?: ActorCompact
  charts: ChatChart[]
  compactions: ChatCompaction[]
  completedAt?: string
  createdAt: string
  durationSeconds?: number
  finding?: InvestigationFinding
  helpers: InvestigationHelper[]
  hypotheses: InvestigationHypothesis[]
  incidentId?: string
  incidentIdentifier?: string
  incidentName?: string
  noteBlockedReason?: string
  notes: InvestigationNote[]
  question?: string
  startedAt?: string
  status: string
  steps: InvestigationStep[]
  stopBlockedReason?: string
  stoppedBecause?: string
  trigger: string
}
