// TypesFromSerializers CacheKey 19969fc709cba6b81551d0d10fa37506
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type RemediationStepKind from '../RemediationStepKind'
import type RemediationStepStatus from '../RemediationStepStatus'

export default interface InvestigationRemediationStep {
  id: string
  action?: string
  dependsOn: number[]
  description: string
  doneBy?: string
  kind: RemediationStepKind
  markDoneBlockedReason?: string
  missing?: string
  position: number
  receipt: { decision: string, at: string } | null
  repository?: string
  result?: string
  status: RemediationStepStatus
  undo?: string
}
