// TypesFromSerializers CacheKey 64530e1e075c3eb1734102bb18845f87
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface InvestigationNoteFile {
  id: string
  kind: string
  name: string
  size: string
  unreadReason: string | null
}
