// TypesFromSerializers CacheKey 596c07b14719339fc3bdf433fc977006
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type InvestigationEvidence from './InvestigationEvidence'

export default interface InvestigationFinding {
  cause?: string
  evidence: InvestigationEvidence[]
  gaps?: string
  outcome?: string
  suggestsIncident: boolean
  summary: string
  verdicts: Record<string, number>
}
