// TypesFromSerializers CacheKey 4a8781a9831a68534dc733ee30910c3a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface InvestigationNotice {
  id: string
  checkName?: string
  dueOn?: string
  investigationId?: string
  lastSaidAt?: string
  lastSeenAt: string
  resourceName?: string
  severity: string
  severityLabel: string
  signal: string
  signalLabel: string
  summary: string
  timesSaid: number
  topic: string
  unsaidReason?: string
}
