// TypesFromSerializers CacheKey 1f7591e3f9b4e1e24bfface6adae0882
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ActorCompact from './ActorCompact'
import type ChatChart from './ChatChart'
import type InvestigationFinding from './InvestigationFinding'
import type InvestigationHypothesis from './InvestigationHypothesis'
import type InvestigationNote from './InvestigationNote'
import type InvestigationStep from './InvestigationStep'

export default interface InvestigationDetail {
  id: string
  asker?: ActorCompact
  charts: ChatChart[]
  completedAt?: string
  createdAt: string
  durationSeconds?: number
  finding?: InvestigationFinding
  hypotheses: InvestigationHypothesis[]
  incidentId?: string
  incidentIdentifier?: string
  incidentName?: string
  noteBlockedReason?: string
  notes: InvestigationNote[]
  question?: string
  startedAt?: string
  status: string
  steps: InvestigationStep[]
  stopBlockedReason?: string
  stoppedBecause?: string
  trigger: string
}
