// TypesFromSerializers CacheKey f5fd6fe0585cc22ef42af549225281a7
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface InvestigationStep {
  failure?: string
  label: string
  position: number
  receipt: { decision: string, at: string } | null
  result?: string
  seconds?: number
  status: string
}
