// TypesFromSerializers CacheKey bd7f5828e453c05d7bf4d7d5bd3b2d52
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface InvestigationHelper {
  id: string
  brief: string
  endedBecause?: string
  report?: string
  startedAt: string
  status: "running" | "reported" | "failed" | "stopped"
  title: string
  toolCallId: string
}
