// TypesFromSerializers CacheKey 1768eeb7a6b4c51d2c494c9454d1c245
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type RemediationStepKind from '../RemediationStepKind'
import type RemediationStepStatus from '../RemediationStepStatus'

export default interface InvestigationRemediationStep {
  id: string
  action?: string
  approvedBy?: string
  arguments?: string
  askAgainBlockedReason?: string
  checking: boolean
  dependsOn: number[]
  description: string
  dismissBlockedReason?: string
  doneBy?: string
  expiresAt?: string
  kind: RemediationStepKind
  lapsed: boolean
  markDoneBlockedReason?: string
  missing?: string
  offers: string[]
  position: number
  receipt: { decision: string, at: string } | null
  repository?: string
  result?: string
  runBlockedReason?: string
  runsItself: boolean
  state?: string
  status: RemediationStepStatus
  undo?: string
  warning?: string
}
