// TypesFromSerializers CacheKey 9642e6dc2a736d0db438305e024af9ab
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface InvestigationCheck {
  id: string
  cadence: string
  deletionBlockedReason?: string
  enabled: boolean
  hour: number
  kind: string
  kindLabel: string
  lastRun: { id: string; status: string; at: string; summary?: string } | null
  name: string
  nextRunAt?: string
  notes?: string
  runBlockedReason?: string
  runs: number
  schedule: string
  timeZone: string
  weekday?: number
}
