// TypesFromSerializers CacheKey b8a7e4180da5b11c2a1a6eedffd1e2c7
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ActorCompact from './ActorCompact'
import type InvestigationNoteFile from './InvestigationNoteFile'

export default interface InvestigationNote {
  id: string
  author?: ActorCompact
  content: string
  createdAt: string
  files: InvestigationNoteFile[]
  takenAt?: string
}
