// TypesFromSerializers CacheKey 5eae9ed3cfbeb1a3fd83c57fd9d6d99e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ActorCompact from './ActorCompact'

export default interface InvestigationNote {
  id: string
  author?: ActorCompact
  content: string
  createdAt: string
  takenAt?: string
}
