// TypesFromSerializers CacheKey 46887f3848891f179de3c5828c20cc58
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type InvestigationEvidence from './InvestigationEvidence'
import type InvestigationRemediationPlan from './InvestigationRemediationPlan'

export default interface InvestigationFinding {
  cause?: string
  evidence: InvestigationEvidence[]
  fix?: InvestigationRemediationPlan
  gaps?: string
  outcome?: string
  suggestsIncident: boolean
  summary: string
  verdicts: Record<string, number>
}
