// TypesFromSerializers CacheKey ba47707e33afdd1cfa3d8cef04bf3254
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface InvestigationListItem {
  id: string
  answer?: string
  askedBy?: string
  createdAt: string
  durationSeconds?: number
  incidentId?: string
  incidentIdentifier?: string
  incidentName?: string
  outcome?: string
  spentCents: number
  status: string
  trigger: string
  turnsUsed: number
}
