// TypesFromSerializers CacheKey fd935dd3e977f45ffd190ddc76b83a5c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface InvestigationHypothesis {
  id: string
  assertion: string
  confidence?: number
  createdAt: string
  settled: boolean
  settledAfterStep?: number
  status: string
  steps: number[]
}
