// TypesFromSerializers CacheKey 268f5dea926d866b4d57504729438bd6
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface InvestigationStep {
  failure?: string
  label: string
  outcome: { kind: string; said: string | null; lines: string[]; total: number; size: number; link: { provider: string; url: string } | null } | null
  position: number
  receipt: { decision: string, at: string } | null
  result?: string
  seconds?: number
  startedAt?: string
  status: string
}
