// TypesFromSerializers CacheKey 90dafa6b9048ab5704d51aab3aadf75e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type RemediationStepKind from '../RemediationStepKind'
import type RemediationStepStatus from '../RemediationStepStatus'

export default interface InvestigationRemediationStep {
  id: string
  action?: string
  approvedBy?: string
  arguments?: string
  askAgainBlockedReason?: string
  checking: boolean
  dependsOn: number[]
  description: string
  dismissBlockedReason?: string
  doneBy?: string
  expiresAt?: string
  kind: RemediationStepKind
  lapsed: boolean
  markDoneBlockedReason?: string
  missing?: string
  offers: string[]
  position: number
  progress: { startedAt: string; live: boolean; total: number; lines: { text: string; at: string | null; result: string | null }[]; changed: string[]; tests: { command: string; passed: boolean }[]; files: { path: string; added: number | null; removed: number | null }[]; finishedAt: string | null; outcome: string | null; pullRequest: string | null; reason: string | null; question: { id: string; text: string; askedAt: string | null; answerDueAt: string | null; status: string; answer: string | null; answeredBy: string | null; byHalon: boolean; answeredAt: string | null } | null; checks: { name: string; status: string }[]; review: { ran: boolean; right: boolean; findings: string[]; unverified: string[]; summary: string | null; sentBack: boolean } | null } | null
  questionBlockedReason?: string
  receipt: { decision: string, at: string } | null
  repository?: string
  result?: string
  runBlockedReason?: string
  runsItself: boolean
  state?: string
  status: RemediationStepStatus
  undo?: string
  warning?: string
}
