// TypesFromSerializers CacheKey 0da1160bff6733ed65f7210c659adefc
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type InvestigationEvidence from './InvestigationEvidence'

export default interface InvestigationFinding {
  cause?: string
  evidence: InvestigationEvidence[]
  gaps?: string
  outcome?: string
  summary: string
  verdicts: Record<string, number>
}
