// TypesFromSerializers CacheKey 00c2d710e8b59188d655a32fb39e17eb
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type RemediationPlanStatus from '../RemediationPlanStatus'
import type InvestigationRemediationStep from './InvestigationRemediationStep'
import type InvestigationRemediationPlan from './InvestigationRemediationPlan'

export default interface InvestigationFixPlan {
  id: string
  appliable: boolean
  appliedAt?: string
  appliedBy?: string
  applyBlockedReason?: string
  cancelBlockedReason?: string
  cancelledAt?: string
  cancelledBy?: string
  isUndo: boolean
  moving: boolean
  status: RemediationPlanStatus
  steps: InvestigationRemediationStep[]
  summary: string
  unattendedReading?: string
  undo?: InvestigationRemediationPlan
  undoBlockedReason?: string
  undoError?: string
  verify?: string
  writingUndo: boolean
}
