// TypesFromSerializers CacheKey cb2829f80c68158b436998b431b0dd80
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface InvestigationHypothesis {
  id: string
  assertion: string
  confidence?: number
  status: string
  steps: number[]
}
