// TypesFromSerializers CacheKey 2064f64647e9eb3b62f6bd73c7aff042
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface InvestigationStep {
  failure?: string
  label: string
  position: number
  receipt: { decision: string, at: string } | null
  result?: string
  seconds?: number
  startedAt?: string
  status: string
}
