// TypesFromSerializers CacheKey 26a0942a628ac05e9ff22b36c2871191
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type RemediationPlanStatus from '../RemediationPlanStatus'
import type InvestigationRemediationStep from './InvestigationRemediationStep'
import type InvestigationRemediationPlan from './InvestigationRemediationPlan'

export default interface InvestigationFixPlan {
  id: string
  appliable: boolean
  appliedAt?: string
  appliedBy?: string
  applyBlockedReason?: string
  isUndo: boolean
  moving: boolean
  status: RemediationPlanStatus
  steps: InvestigationRemediationStep[]
  summary: string
  undo?: InvestigationRemediationPlan
  undoBlockedReason?: string
  undoError?: string
  verify?: string
  writingUndo: boolean
}
