// TypesFromSerializers CacheKey 32473f58ce1329ae67a5ab587130443d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface LifecycleStage {
  description: string
  key: string
  name: string
  open: boolean
}
