// TypesFromSerializers CacheKey a59a12cb51b6a6d714b0d922293fde71
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface LifecycleStage {
  description: string
  key: string
  name: string
}
