// TypesFromSerializers CacheKey 6574f90fabee93e415d9120b683d0c4b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ResourceMapKind from '../ResourceMapKind'
import type MapSearchType from '../MapSearchType'

export default interface MapSearchResult {
  id: string
  about?: string
  account?: string
  catalogType?: string
  environment?: string
  href: string
  kind?: ResourceMapKind
  providerName?: string
  title: string
  type: MapSearchType
  why: string
}
