// TypesFromSerializers CacheKey 93050090988cb54b079231a2d98b52ce
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface MemorySubjectOption {
  label: string
  value: string
}
