// TypesFromSerializers CacheKey cd88d3f997434417056ba960fe14e7c8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface OnboardingStep {
  key: "account" | "ai" | "stack" | "permissions" | "halon" | "slack" | "test_incident"
  note?: string
  state: "done" | "skipped" | "unavailable" | "current" | "waiting"
}
