// TypesFromSerializers CacheKey f79624772ec3646b0c67e690e69ee2e8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface OnboardingStep {
  finished: boolean
  key: "account" | "ai" | "stack" | "permissions" | "halon" | "slack" | "test_incident"
  note?: string
  state: "done" | "skipped" | "current" | "waiting"
}
