// TypesFromSerializers CacheKey 04d20db3fdd88b9220edbde5c2ac6659
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface OnboardingStep {
  key: "account" | "ai" | "stack" | "permissions" | "halon" | "slack" | "test_incident"
  note?: string
  state: "done" | "skipped" | "current" | "waiting"
}
