// TypesFromSerializers CacheKey 6cbfa0bcc3cdaa5e499702b7685a2acf
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type IntegrationCardRow from './IntegrationCardRow'

export default interface OnboardingCategory {
  connectedBlockedReason?: string
  halon: string
  name: string
  required: boolean
  rows: IntegrationCardRow[]
  slug: string
  tagline: string
  unusedBlockedReason?: string
}
