// TypesFromSerializers CacheKey b653675921fdf343f93283374fa49edd
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface OnCallSettings {
  alertInvestigationsEnabled: boolean
  alertStormCeilingCents: number
  onCallPagingEnabled: boolean
  stormCommittedCents: number
}
