// TypesFromSerializers CacheKey 4ddb9f826df2d3546c2875baf81ae626
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface OperatorProcessEntry {
  at: string
  detail?: string
  key: string
  kind: "alert" | "incident" | "workflow" | "step" | "webhook" | "platform" | "halon"
  redeliverId?: string
  retryStepId?: string
  technical?: string
  title: string
  tone: "ok" | "info" | "warn" | "bad" | "idle"
}
