// TypesFromSerializers CacheKey 7e2f5f9c13c90d35a73366e188b23b9b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface OperatorFindMatch {
  id: string
  href: string
  kind: "incident" | "run" | "chat" | "workflow"
  label: string
  place: string
  via?: string
}
