// TypesFromSerializers CacheKey 9e5990e8736311a446c92c4e3f22946b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface OperatorWorkflow {
  id: string
  cancellationReason?: string
  createdAt: string
  events: { id: string; at: string; eventType: string; stepName: string | null; note: string | null; failed: boolean }[]
  failedStep?: string
  incidentId?: string
  pauseReason?: string
  state: "pending" | "running" | "paused" | "succeeded" | "failed" | "cancelled"
  steps: { id: string; name: string; status: "pending" | "running" | "succeeded" | "failed" | "skipped" | "cancelled"; attempts: number; maxAttempts: number | null; lastError: string | null; skipReason: string | null; seconds: number | null; dependsOn: string[]; column: number; row: number }[]
  stepsDone: number
  stepsTotal: number
  subjectLabel: string
  workflowClass: string
}
