// TypesFromSerializers CacheKey a759494e7ec4201d54d52fc59e4225bf
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface OperatorIncidentRow {
  id: string
  declaredAt?: string
  identifier: string
  name: string
  problems: number
  status: string
  workspaceName: string
}
