// TypesFromSerializers CacheKey 37dc4513b4162ca00916c345370fbb46
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface OperatorProcessEntry {
  at: string
  detail?: string
  key: string
  kind: "alert" | "incident" | "workflow" | "step" | "webhook" | "platform" | "halon"
  redeliverId?: string
  retryStepId?: string
  runId?: string
  technical?: string
  title: string
  tone: "ok" | "info" | "warn" | "bad" | "idle"
}
