// TypesFromSerializers CacheKey 143f312a306fc795731bb8633e6f66b8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface OperatorHalonChat {
  id: string
  incidentLabel?: string
  kind: "channel" | "personal" | "mcp"
  spentMicros: number
  title: string
  turns: number
  updatedAt: string
  workspaceName: string
}
