// TypesFromSerializers CacheKey ad48b1d238648e97cc90a9e504d816d3
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type OperatorTraceSpan from './OperatorTraceSpan'

export default interface OperatorTraceGroup {
  endedAt?: string
  key: string
  spans: OperatorTraceSpan[]
  startedAt?: string
  title: string
}
