// TypesFromSerializers CacheKey 41523e1ca7c085abc79f9efc6d1ce428
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface OperatorTraceSpan {
  detail?: string
  endedAt?: string
  facts: { label: string; value: string }[]
  hasBody: boolean
  key: string
  kind: "job" | "facts" | "model" | "tool" | "theory" | "check" | "answer" | "stop" | "post" | "platform" | "verdict" | "ask" | "reply" | "run"
  runId?: string
  startedAt: string
  title: string
  tone: "ok" | "info" | "warn" | "bad" | "idle"
}
