// TypesFromSerializers CacheKey d9e0520999329db176682690f8de492b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface OperatorWorkflowRow {
  id: string
  createdAt: string
  failedStep?: string
  incidentId?: string
  state: "pending" | "running" | "paused" | "succeeded" | "failed" | "cancelled"
  stepsDone: number
  stepsTotal: number
  subjectLabel: string
  workflowClass: string
}
