// TypesFromSerializers CacheKey 8737d2f74c6f75dbe1fa32beae59f943
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface PackRequest {
  id: string
  giveBlockedReason?: string
  packDescription?: string
  packName: string
  requestedAt: string
  requesterName: string
}
