// TypesFromSerializers CacheKey 5f0121a04f31b3ab56116a8925a65727
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface PolicyRule {
  id: string
  conditions: { field: string; operator: "is_one_of" | "contains" | "starts_with" | "matches_regex" | "is_empty"; value?: string | string[] }[]
  enabled: boolean
  outcome: { action: "auto_create_incident" | "attach_to_incident" | "notify_only" | "drop"; severityId?: string; notify?: { type: "channel" | "member" | "team" | "owning_team"; channelId?: string; channelName?: string; memberId?: string; entryId?: string; of?: string }; invite?: { type: "member" | "team" | "owning_team"; memberId?: string; entryId?: string; of?: string }[] }
  priority: number
}
