// TypesFromSerializers CacheKey e88ab740d73d34300ad7fde2f2c29c1f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface PolicyRule {
  id: string
  conditions: { field: string; operator: string; value?: string | string[] }[]
  enabled: boolean
  outcome: { action: string; severityId?: string; notify?: { type: string; channelId?: string; memberId?: string; entryId?: string; of?: string }; invite?: { type: string; memberId?: string; entryId?: string; of?: string }[] }
  priority: number
}
