// TypesFromSerializers CacheKey 24b6229fdba28786ee924fc51ba907ca
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Postmortem {
  id: string
  createdAt: string
  generatedBy: string
  generationError?: string
  generationState?: "generating" | "failed"
  htmlContent?: string
  status: "draft" | "in_progress" | "in_review" | "completed"
  title: string
  updatedAt: string
}
