// TypesFromSerializers CacheKey 647c8685dff2a3f07b4b08a2a094d5f1
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface PostmortemUpdate {
  id: string
  createdAt: string
  editedBy: string
  htmlContent?: string
  updateType: "generated" | "edited" | "ai_edited"
}
