// TypesFromSerializers CacheKey 8ea2af79c5eacf78ed6f7e49d2f4e23c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface PostmortemUpdate {
  id: string
  changedSections: string[]
  createdAt: string
  editedBy: string
  updateType: "generated" | "edited" | "ai_edited"
}
