// TypesFromSerializers CacheKey c74318bded6f2c046449413f0c6bc58a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Postmortem {
  id: string
  createdAt: string
  generatedBy: string
  generationError?: string
  generationNote?: string
  generationState?: "generating" | "failed"
  htmlContent?: string
  status: "draft" | "in_progress" | "in_review" | "completed"
  title: string
  updatedAt: string
  version: number
}
