// TypesFromSerializers CacheKey ace850f8ba530dbe30e2c0069dee50fd
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface PostmortemUpdate {
  id: string
  createdAt: string
  editedBy: string
  htmlContent?: string
  updateType: "generated" | "edited"
}
