// TypesFromSerializers CacheKey 2b9a2e29c95de62aac1395aa2cbf459d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Postmortem {
  id: string
  createdAt: string
  generatedBy: string
  generationError?: string
  generationState?: "generating" | "failed"
  htmlContent?: string
  status: "draft" | "in_progress" | "in_review" | "completed"
  title: string
  updatedAt: string
  version: number
}
