// TypesFromSerializers CacheKey e32758a449f2d72d8cd596b3f6afd299
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Principal {
  id: string
  grants: { id: string; kind: string; targetId: string; label: string; riskLevel: string | null; actionCount: number; environmentIds: string[] }[]
  implicitAuthority: string
  kind: string
  name: string
  principalType: string
}
