// TypesFromSerializers CacheKey dff676e6f64d92eb62645a3b4eccb5ed
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Principal {
  id: string
  grants: { id: string; kind: string; targetId: string; label: string; title: string | null; description: string | null; riskLevel: string | null; actionCount: number; environmentIds: string[]; expiresAt: string | null; expired: boolean }[]
  implicitAuthority: string
  kind: string
  name: string
}
