// TypesFromSerializers CacheKey ec11761162b56f03481a307f7851fb43
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Principal {
  id: string
  defaultAccess: { actionId: string; actionKey: string; title: string; note: string; grantId: string | null }[]
  grants: { id: string; kind: string; targetId: string; label: string; title: string | null; description: string | null; riskLevel: string | null; actionCount: number; environmentIds: string[]; expiresAt: string | null; expired: boolean }[]
  implicitAuthority: string
  kind: string
  name: string
}
