// TypesFromSerializers CacheKey 71266a5a862af531d284069004778a85
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface RepositorySetup {
  id: string
  commands: string[]
  derivedAt?: string
  derivedFrom?: string
  editedAt?: string
  env: Record<string, string>
  notes: string[]
  repository: string
  services: { name: string; image: string | null; port: number | null; env: Record<string, string> }[]
  unstartableServices: string[]
}
