// TypesFromSerializers CacheKey fab391e87bdfd6424f1f11daf19712c6
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ResourceMapCertainty from '../ResourceMapCertainty'
import type ResourceMapOrigin from '../ResourceMapOrigin'
import type ResourceMapRelation from '../ResourceMapRelation'

export default interface ResourceMapLink {
  id: string
  certainty?: ResourceMapCertainty
  clues: string[]
  foundBy?: string
  fromId: string
  note?: string
  origin: ResourceMapOrigin
  relation: ResourceMapRelation
  removalBlockedReason?: string
  toId: string
  unconfirmed: boolean
  variables: string[]
}
