// TypesFromSerializers CacheKey 7aba6b5c4e39af602a27c6bcf0212c66
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ResourceMapHealth from '../ResourceMapHealth'
import type ResourceMapKind from '../ResourceMapKind'
import type ResourceMapEntry from './ResourceMapEntry'
import type ResourceMapChange from './ResourceMapChange'
import type ResourceMapIncident from './ResourceMapIncident'
import type ResourceMapPastIncident from './ResourceMapPastIncident'

export default interface ResourceMapResource {
  id: string
  account: string
  catalogEntries: ResourceMapEntry[]
  dependentIds: string[]
  environment?: string
  externalId: string
  facts: string[][]
  firstSeenAt: string
  health: ResourceMapHealth
  instructions: string[][]
  kind: ResourceMapKind
  lastChange?: ResourceMapChange
  lastSeenAt: string
  memories: string[][]
  name: string
  openIncidents: ResourceMapIncident[]
  pastIncidents: ResourceMapPastIncident[]
  provider: string
  providerColor?: string
  providerMark?: string
  providerName: string
  recentIncidentCount: number
  status?: string
  statusLabel?: string
  suggestedDependentIds: string[]
  url?: string
}
