// TypesFromSerializers CacheKey eb04435976a32870448f29357dc3dbe5
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface ResourceMapConnection {
  id: string
  baselineError?: string
  error?: string
  gaps: string[]
  liveUpdates: { on: boolean; lastEventAt: string | null; reason: string | null } | null
  name: string
  sweptAt?: string
}
