// TypesFromSerializers CacheKey c6a8a90941844afe951d24b1ecceaf7d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface ResourceMapEntry {
  id: string
  name: string
  typeName: string
  typeSlug: string
}
