// TypesFromSerializers CacheKey a731e06e5e802d75484e3c9184e79d35
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ResourceMapTimelineKind from '../ResourceMapTimelineKind'
import type ResourceMapTimelineSource from '../ResourceMapTimelineSource'

export default interface ResourceMapTimelineEntry {
  id: string
  at: string
  by?: string
  kind: ResourceMapTimelineKind
  label: string
  link?: string
  source: ResourceMapTimelineSource
  what: string
}
