// TypesFromSerializers CacheKey 989c1a1f1bcaf568d0549c6624c5e890
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ResourceMapCertainty from '../ResourceMapCertainty'
import type ResourceMapOrigin from '../ResourceMapOrigin'
import type ResourceMapRelation from '../ResourceMapRelation'

export default interface ResourceMapLink {
  id: string
  certainty?: ResourceMapCertainty
  clues: string[]
  foundBy?: string
  fromId: string
  note?: string
  origin: ResourceMapOrigin
  relation: ResourceMapRelation
  removalBlockedReason?: string
  toId: string
  unconfirmed: boolean
}
