// TypesFromSerializers CacheKey 605dd4bdedf957629c6cc863e7506a5b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface ResourceMapIncident {
  id: string
  identifier: string
  name: string
}
