// TypesFromSerializers CacheKey ff6fca81ec855fbc5beaf4a159b2fb56
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface ResourceMapEntry {
  id: string
  name: string
  owners: string[]
  purpose?: string
  typeName: string
  typeSlug: string
}
