// TypesFromSerializers CacheKey 77c7aac672b526192f20f4b35e35ce0c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ResourceMapLogLevel from '../ResourceMapLogLevel'

export default interface ResourceMapLogTemplate {
  id: string
  level?: ResourceMapLogLevel
  lines: number
  samples: number
  template: string
}
