// TypesFromSerializers CacheKey 4e11f9bd3e24651c79cce85cbe46a4e3
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface ResourceMapPastIncident {
  id: string
  endedAt: string
  identifier: string
  name: string
  outcome?: string
  outcomeSource?: string
}
