// TypesFromSerializers CacheKey 96ccc7e0cbb84212af192142e16c9dac
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface ResourceMapBaseline {
  id: string
  high: string
  label: string
  peak: string
  typical: string
  windowTo: string
}
