// TypesFromSerializers CacheKey dc9ad592616b889fff7ccc7290b07f3a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ChatChart from './ChatChart'

export default interface ResourceMapCheckOutcome {
  approvalId?: string
  charts: ChatChart[]
  failed: boolean
  headline?: string
  link?: string
  refusal?: string
  text?: string
}
