// TypesFromSerializers CacheKey a4066fa2f3dd387e25ec58ae8b43d3dc
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ResourceMapOrigin from '../ResourceMapOrigin'
import type ResourceMapRelation from '../ResourceMapRelation'

export default interface ResourceMapLink {
  id: string
  foundBy?: string
  fromId: string
  note?: string
  origin: ResourceMapOrigin
  relation: ResourceMapRelation
  removalBlockedReason?: string
  toId: string
  unconfirmed: boolean
}
