// TypesFromSerializers CacheKey 54daffce780a9425e24cfc105dc960d1
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface ResourceMapConnection {
  id: string
  error?: string
  gaps: string[]
  name: string
  sweptAt?: string
}
