// TypesFromSerializers CacheKey 33bf6365ecaaaad3a0d6b6a15a35cf3c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface ResourceMapCheck {
  available: boolean
  connection?: string
  key: string
  label: string
  normal?: string
  reads?: string
  readsMetric: boolean
  runBlockedReason?: string
}
