// TypesFromSerializers CacheKey 92b98dc5cbffd43f86423afbe753637a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ResourceMapChangeKind from '../ResourceMapChangeKind'

export default interface ResourceMapChange {
  id: string
  detail?: string
  fromValue?: string
  happenedAt: string
  kind: ResourceMapChangeKind
  resourceId: string
  resourceName: string
  toValue?: string
}
