// TypesFromSerializers CacheKey 171aeede2587f3b5123fbc4368bd1687
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ResourceMapChangeKind from '../ResourceMapChangeKind'

export default interface ResourceMapChange {
  id: string
  fromValue?: string
  happenedAt: string
  kind: ResourceMapChangeKind
  resourceId: string
  resourceName: string
  toValue?: string
}
