// TypesFromSerializers CacheKey 2aecf048732250f78a4cd18154c4c5ee
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface ResourceMapConnection {
  id: string
  baselineError?: string
  error?: string
  gaps: string[]
  liveUpdates: { on: boolean; lastEventAt: string | null; reason: string | null } | null
  logPatternsError?: string
  name: string
  sweptAt?: string
}
