// TypesFromSerializers CacheKey e040ab2c03c7639e6db6187ab12e01cd
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface RunbookPlace {
  kind: string
  name: string
}
