// TypesFromSerializers CacheKey 8f0f42fa47edf95a698284c38db3735c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface RunbookWatchRead {
  history: boolean
  label: string
  name: string
}
