// TypesFromSerializers CacheKey 3a3617e03e97f6412eaff51003e83031
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface RunbookCustomField {
  id: string
  catalogTypeId?: string
  entries: { id: string; name: string }[]
  fieldType: string
  key: string
  name: string
  options: { id: string; name: string }[]
}
