// TypesFromSerializers CacheKey 899c39dc984cc9de79874806545ce518
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type IncidentConditionSettings from '../IncidentConditionSettings'
import type RunbookStepSettings from './RunbookStepSettings'

export default interface RunbookSettings {
  id: string
  conditions?: IncidentConditionSettings[]
  content?: string
  deletionBlockedReason?: string
  enabled: boolean
  externalUrl?: string
  name: string
  position: number
  slug: string
  steps: RunbookStepSettings[]
  summary?: string
  usageCount: number
}
