// TypesFromSerializers CacheKey 1b09186cc39258aeb208bf48a2da6207
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface RunbookStepSettings {
  id: string
  arguments: Record<string, unknown>
  instruction?: string
  position: number
  title: string
  tool?: string
}
