// TypesFromSerializers CacheKey 6f159efca7d9bf29c3095b3ca81c68ec
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type IncidentConditionSettings from '../IncidentConditionSettings'
import type RunbookStepSettings from './RunbookStepSettings'

export default interface RunbookSettings {
  id: string
  conditions?: IncidentConditionSettings[]
  content?: string
  externalUrl?: string
  name: string
  position: number
  slug: string
  steps: RunbookStepSettings[]
  summary?: string
}
