// TypesFromSerializers CacheKey 1fd819c606d226a1c10e7fd6a14773c8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface RunbookToolChoice {
  description: string
  fields: { key: string; kind: "text" | "number" | "select" | "toggle" | "list" | "kept" | "resource"; options: string[]; required: boolean; description: string | null }[]
  group: string
  name: string
}
