// TypesFromSerializers CacheKey c88dd2a843609b58daa8aa9c23ae68e9
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface RunbookStepSettings {
  id: string
  instruction?: string
  position: number
  title: string
}
