// TypesFromSerializers CacheKey 5607b44e15a5063c33b46401ccd68b95
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface RunbookCustomField {
  id: string
  catalogTypeId?: string
  entries: { id: string; name: string }[]
  fieldType: string
  name: string
  options: { id: string; name: string }[]
  slug: string
}
