// TypesFromSerializers CacheKey 43302d74ac5aff2d6685accacedb6928
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type IncidentConditionSettings from '../IncidentConditionSettings'
import type RunbookStepSettings from './RunbookStepSettings'

export default interface RunbookSettings {
  id: string
  alwaysAttach: boolean
  conditions?: IncidentConditionSettings[]
  content?: string
  deletionBlockedReason?: string
  enabled: boolean
  externalUrl?: string
  name: string
  position: number
  slug: string
  steps: RunbookStepSettings[]
  summary?: string
  usageCount: number
}
