// TypesFromSerializers CacheKey e620e17d87faef3066b2e839905dbb63
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface RunbookCustomField {
  id: string
  catalogTypeId?: string
  entries: { id: string; name: string }[]
  fieldType: string
  key: string
  name: string
  options: string[]
}
