// TypesFromSerializers CacheKey 2ec09bf4959c22b32f0caf2f4e58910f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface SeverityCompact {
  color?: string
  name: string
  rank: number
}
