// TypesFromSerializers CacheKey 4eafa2d11bf9b9f83c102bd7ce265adb
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface SeverityCompact {
  color?: string
  name: string
  rank: number
  signalBars: number
}
