// TypesFromSerializers CacheKey 31df152acaae9778ced211b2f8fc13f9
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface SeverityCompact {
  name: string
  rank: number
}
