// TypesFromSerializers CacheKey f1e3554878bf560b0ab1f00ced06dfc8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface SeverityDetail {
  color: string
  name: string
  rank: number
}
