// TypesFromSerializers CacheKey 361d3512b4298af24c737c1711a2257c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface SeverityOption {
  name: string
  slug: string
}
