// TypesFromSerializers CacheKey 8636163e8d925adf10d15a127e4fd3ab
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface SignInMethod {
  id: string
  addedAt: string
  email?: string
  label: string
  lastUsedAt?: string
  provider: string
  removalBlockedReason?: string
}
