// TypesFromSerializers CacheKey 4d02833080c4bad5bce6185c97b3351f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface StatusCompact {
  color: string
  lifecycleStage: "triage" | "active" | "closed" | "canceled"
  name: string
  slug: string
}
