// TypesFromSerializers CacheKey 55258ee16605a48f1d6a329bb3da1611
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface StatusCompact {
  lifecycleStage: string
  name: string
}
