// TypesFromSerializers CacheKey f98f009ecbd4f0571be92888e74007b6
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface StatusCompact {
  color: string
  lifecycleStage: string
  name: string
}
