// TypesFromSerializers CacheKey 82ee59d99df053cd899d7a5a7e80d911
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface StatusDetail {
  color: string
  lifecycleStage: string
  name: string
}
