// TypesFromSerializers CacheKey 1e07f8146ee75d6318713a029e3a5882
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface StatusDetail {
  color: string
  lifecycleStage: "triage" | "active" | "closed" | "canceled"
  name: string
}
