// TypesFromSerializers CacheKey 41a06b5344f05e5187dc13cbc24a743d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface TimelineEvent {
  id: string
  actor: string
  changes?: { field: string; before: string; after: string }[]
  createdAt: string
  description: string
  details?: string
  eventType: string
  file?: { name: string; mimeType: string | null; slackPermalink: string | null; downloadUrl: string | null; byteSize: number | null }
}
