// TypesFromSerializers CacheKey fd2041d0af08407960c3d7d277f224f5
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface TimelineEvent {
  id: string
  action?: { id: string; description: string; status: string; assignee: { name: string; initials: string; avatarUrl?: string } | null }
  actor: string
  actorAvatarUrl?: string
  automated: boolean
  changes?: { field: string; before: string; after: string }[]
  createdAt: string
  description: string
  details?: string
  eventType: "incident.created" | "incident.updated" | "incident.accepted" | "lead.assigned" | "role.assigned" | "role.unassigned" | "action.created" | "action.picked_up" | "action.completed" | "action.reassigned" | "incident.escalated" | "incident.resolved" | "incident.reopened" | "incident.canceled" | "postmortem.generated" | "postmortem.edited" | "relationship.created" | "incident.marked_duplicate" | "incident.merged_into" | "message.pinned" | "message.unpinned" | "message.file_shared" | "incident.escalation_acknowledged" | "incident.escalation_nudged" | "alert.attached" | "alert.resolved" | "runbook.attached" | "runbook.applied" | "milestone.noted"
  file?: { name: string; mimeType: string | null; slackPermalink: string | null; downloadUrl: string | null; byteSize: number | null }
  milestone?: { kind: "hypothesis" | "finding" | "root_cause" | "mitigation" | "decision" | "blocker" | "impact" | "recovery"; statement: string; quote: string | null; permalink: string | null; dismissedAt: string | null; dismissedBy: string | null }
  person?: { name: string; initials: string; avatarUrl?: string }
  pin?: { text: string | null; permalink: string | null }
  subject?: { label: string; href: string | null }
}
