// TypesFromSerializers CacheKey edcf5ebead53cbfc1d6d6558f76a076d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface TimelineEvent {
  id: string
  actor: string
  actorAvatarUrl?: string
  changes?: { field: string; before: string; after: string }[]
  createdAt: string
  description: string
  details?: string
  eventType: "incident.created" | "incident.updated" | "incident.accepted" | "lead.assigned" | "role.assigned" | "role.unassigned" | "action.created" | "action.picked_up" | "action.completed" | "action.reassigned" | "incident.escalated" | "incident.resolved" | "incident.reopened" | "incident.canceled" | "postmortem.generated" | "postmortem.edited" | "relationship.created" | "incident.marked_duplicate" | "incident.merged_into" | "message.pinned" | "message.unpinned" | "message.file_shared" | "incident.escalation_acknowledged" | "incident.escalation_nudged" | "alert.attached" | "alert.resolved" | "runbook.attached" | "runbook.applied"
  file?: { name: string; mimeType: string | null; slackPermalink: string | null; downloadUrl: string | null; byteSize: number | null }
}
