// TypesFromSerializers CacheKey 5e7c8897228aac26b382d7b4fc3eec60
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ResourceMapKind from '../ResourceMapKind'

export default interface UnattendedRuleResource {
  id: string
  capabilities: ("rollback" | "restart")[]
  kind: ResourceMapKind
  name: string
}
