// TypesFromSerializers CacheKey a11651d0e9c3cb16238f73a650070de4
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface UnattendedRule {
  id: string
  blockedReason?: string
  capability: "rollback" | "restart"
  createdByName?: string
  deleteBlockedReason?: string
  enabled: boolean
  metric: string
  minutes: number
  resourceId: string
  resourceName: string
  sentence: string
  threshold: number
  usageCount: number
}
