// TypesFromSerializers CacheKey e87584b2ecee73ffa99994e4a2427f32
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface WebhookDelivery {
  id: string
  attemptedAt: string
  deliveredAt?: string
  errorMessage?: string
  eventType: string
  responseCode?: number
  state: "pending" | "in_progress" | "succeeded" | "failed"
}
