// TypesFromSerializers CacheKey 38b2a3a3e9b37bc94afeabc47aa8aac8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type WebhookDelivery from './WebhookDelivery'

export default interface Webhook {
  id: string
  active: boolean
  createdAt: string
  deliveries: WebhookDelivery[]
  deliveryCount: number
  name: string
  subscribedEvents: string[]
  url: string
}
