// TypesFromSerializers CacheKey f4df9b4bc895934f351a1c60623faf99
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type WebhookDelivery from './WebhookDelivery'

export default interface Webhook {
  id: string
  active: boolean
  createdAt: string
  deliveries: WebhookDelivery[]
  name: string
  signingSecret: string
  subscribedEvents: string[]
  url: string
}
