// TypesFromSerializers CacheKey 6b789bc83e14512a440d8dc94801f29a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface WebhookDelivery {
  id: string
  deliveredAt: string
  errorMessage?: string
  eventType: string
  responseCode?: number
  state: "completed" | "errored"
}
