// TypesFromSerializers CacheKey 807f03085174465360c24afd79a9922e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type WebhookDelivery from './WebhookDelivery'

export default interface Webhook {
  id: string
  active: boolean
  createdAt: string
  deliveries: WebhookDelivery[]
  deliveryCount: number
  name: string
  signingSecret: string
  subscribedEvents: string[]
  url: string
}
