// TypesFromSerializers CacheKey 4a6cabfaabbadb2ae739e1e2693a49ab
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface WorkspaceSettings {
  archiveChannelDelay: string
  transcriptAccessEnabled: boolean
  transcriptRetentionDays?: number
  webSearchEnabled: boolean
}
