// TypesFromSerializers CacheKey f7f7c55f9e0e50242f9fe76e4b38d53c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface WorkspaceSettings {
  archiveChannelDelay: string
  chatTeamName?: string
  codeFixAgent?: string
  codeFixAgentBlockedReason?: string
  codeFixAgents: { value: string | null; label: string }[]
  halonRegressionEnabled: boolean
  issueCreation: "never" | "asked" | "follow_ups" | "all"
  issueCreationBlockedReason?: string
  issueCreations: { value: "never" | "asked" | "follow_ups" | "all"; label: string }[]
  issueTracker?: string
  issueTrackerTarget: Record<string, string>
  issueTrackers: { value: string | null; label: string; fields: { key: string; label: string; placeholder: string; hint: string; required: boolean }[]; steps: string[] }[]
  issueWebhookAutomatic: boolean
  issueWebhookBlockedReason?: string
  issueWebhookRegistered: boolean
  issueWebhookSecretSet: boolean
  memoryExpiryDays?: number
  transcriptAccessEnabled: boolean
  transcriptRetentionDays?: number
  webSearchEnabled: boolean
}
