// TypesFromSerializers CacheKey a48afdcb028bb1847aa0d2d2e9a738ab
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface WorkspaceAiAccount {
  id: string
  deletionConsequence: string
  enabled: boolean
  keySummary?: string
  kind: string
  label: string
  lastError?: string
  lastUsedAt?: string
  models: { main: string; fast: string }
  name: string
  provider: string
  providerName: string
  settings: Record<string, string>
  state: "verified" | "unchecked" | "out_of_credit" | "failing" | "disabled"
  verifiedAt?: string
}
