// TypesFromSerializers CacheKey e835164df0b145d98f5695fdb495cf1d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface WorkspaceSettings {
  archiveChannelDelay: string
  transcriptAccessEnabled: boolean
  transcriptRetentionDays?: number
}
