// TypesFromSerializers CacheKey 741a20b718887fa713e2a4db883e127b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface WorkspaceMembership {
  id: string
  avatarUrl?: string
  email: string
  joinedAt: string
  name: string
  role: string
}
