// TypesFromSerializers CacheKey a19c30b80ec42b224f0cde704b6a447f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface WorkspaceInvitation {
  id: string
  email: string
  expired: boolean
  expiresAt: string
  invitedByName?: string
  sentAt: string
}
