module Slack
  module Messages
    module Postmortem
      def self.build(incident, postmortem)
        duration_text = Formatting.format_duration(incident.time_to_resolve)
        lead_text = incident.lead ? "<@#{incident.lead.platform_user_id}>" : "Unassigned"

        title_line = "*#{postmortem.title}*"
        meta_line  = "Duration: #{duration_text}  |  Severity: #{incident.incident_severity.name}  |  Lead: #{lead_text}"

        blocks = [
          { type: "header", text: { type: "plain_text", text: ":clipboard: Postmortem — #{incident.identifier}", emoji: true } },
          { type: "section", text: { type: "mrkdwn", text: "#{title_line}\n#{meta_line}" } }
        ]

        url = postmortem_dashboard_url(incident)
        if url
          blocks << {
            type: "actions",
            elements: [
              {
                type: "button",
                text: { type: "plain_text", text: "View full postmortem", emoji: true },
                url: url,
                style: "primary"
              }
            ]
          }
        end

        blocks << {
          type: "context",
          elements: [ { type: "mrkdwn", text: ":sparkles: _Generated by Firefight AI_" } ]
        }

        blocks
      end

      def self.postmortem_dashboard_url(incident)
        host = ENV["APP_HOST"].presence
        return nil unless host

        protocol = ENV.fetch("APP_PROTOCOL", "https")
        Rails.application.routes.url_helpers.incident_postmortem_url(
          incident_id: incident.id,
          host: host,
          protocol: protocol
        )
      rescue StandardError => e
        Rails.logger.warn({ event: "postmortem_message.url_build_failed", error: e.message }.to_json)
        nil
      end
      private_class_method :postmortem_dashboard_url
    end
  end
end
