module Slack
  module Messages
    module Postmortem
      def self.build(incident, postmortem)
        duration_text = Formatting.format_duration(incident.time_to_resolve)
        lead_text = incident.lead ? "<@#{incident.lead.platform_user_id}>" : "Unassigned"

        blocks = [
          { type: "header", text: { type: "plain_text", text: ":clipboard: Postmortem — #{incident.identifier}", emoji: true } },
          { type: "divider" },
          { type: "section", text: { type: "mrkdwn", text: "*#{postmortem.title}*" } }
        ]
        blocks << { type: "section", text: { type: "mrkdwn", text: Formatting.truncate_block_text(postmortem.summary) } } if postmortem.summary.present?

        blocks << { type: "divider" }
        blocks << {
          type: "context",
          elements: [
            { type: "mrkdwn", text: "Duration: #{duration_text}  |  Severity: #{incident.incident_severity.name}  |  Lead: #{lead_text}" }
          ]
        }
        blocks << { type: "divider" }
        blocks << {
          type: "context",
          elements: [ { type: "mrkdwn", text: ":sparkles: _Generated by AI_ · View full postmortem in the dashboard" } ]
        }

        blocks
      end
    end
  end
end
