import { useEffect, useMemo, useState } from "react"
import { IconArrowLeft, IconClock } from "@tabler/icons-react"
import HtmlDiff from "htmldiff-js"

import type { PostmortemUpdate } from "@/types/serializers"
import { Button } from "@/components/ui/button"
import { Separator } from "@/components/ui/separator"
import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetHeader,
  SheetTitle,
} from "@/components/ui/sheet"
import { Skeleton } from "@/components/ui/skeleton"
import { incidentPostmortemRevisionsPath } from "@/lib/routes"

const updateTypeLabels: Record<string, string> = {
  generated: "Generated by AI",
  edited: "Edited",
}

export function RevisionsSheet({
  incidentId,
  currentHtml,
  open,
  onOpenChange,
  onRestore,
}: {
  incidentId: string
  currentHtml: string
  open: boolean
  onOpenChange: (open: boolean) => void
  onRestore: (html: string) => void
}) {
  const [revisions, setRevisions] = useState<PostmortemUpdate[]>([])
  const [loading, setLoading] = useState(false)
  const [selectedId, setSelectedId] = useState<string | null>(null)

  useEffect(() => {
    if (!open) {
      return
    }

    const controller = new AbortController()
    setLoading(true)
    fetch(incidentPostmortemRevisionsPath(incidentId), { signal: controller.signal })
      .then((res) => res.json())
      .then((data) => {
        setRevisions(data)
        setLoading(false)
      })
      .catch((err) => {
        if (err.name !== "AbortError") {
          setLoading(false)
        }
      })

    return () => controller.abort()
  }, [open, incidentId])

  const selectedRevision = selectedId ? revisions.find((revision) => revision.id === selectedId) : null
  const selectedIndex = selectedRevision ? revisions.indexOf(selectedRevision) : -1

  const diffHtml = useMemo(() => {
    if (!selectedRevision?.htmlContent) {
      return null
    }
    const olderHtml = selectedRevision.htmlContent
    // revisions are newest-first. The "next" version is the previous index, or the live editor content
    const newerHtml = selectedIndex === 0 ? currentHtml : (revisions[selectedIndex - 1]?.htmlContent ?? currentHtml)
    try {
      return HtmlDiff.execute(olderHtml, newerHtml)
    } catch {
      return null
    }
  }, [selectedRevision, selectedIndex, revisions, currentHtml])

  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent className="sm:max-w-lg overflow-y-auto">
        <SheetHeader>
          <SheetTitle>Revisions</SheetTitle>
          <SheetDescription>
            {selectedRevision ? "Viewing revision" : "Select a revision to preview"}
          </SheetDescription>
        </SheetHeader>
        <div className="flex flex-col gap-4 px-6 pb-6">
          {loading && (
            <div className="space-y-3">
              {Array.from({ length: 4 }).map((_, index) => (
                <Skeleton key={index} className="h-12 w-full" />
              ))}
            </div>
          )}

          {!loading && !selectedRevision && (
            <div className="space-y-1">
              {revisions.map((rev) => (
                <button
                  key={rev.id}
                  onClick={() => setSelectedId(rev.id)}
                  className="flex w-full items-center gap-3 rounded-lg border p-3 text-left hover:bg-muted/50 transition-colors"
                >
                  <IconClock className="size-4 text-muted-foreground shrink-0" />
                  <div className="flex-1 min-w-0">
                    <div className="text-sm font-medium">{rev.editedBy}</div>
                    <div className="text-xs text-muted-foreground">
                      {updateTypeLabels[rev.updateType] ?? rev.updateType}
                    </div>
                  </div>
                  <span className="text-xs text-muted-foreground tabular-nums shrink-0">
                    {new Date(rev.createdAt).toLocaleDateString("en-US", {
                      month: "short", day: "numeric", hour: "2-digit", minute: "2-digit",
                    })}
                  </span>
                </button>
              ))}
              {revisions.length === 0 && (
                <p className="text-sm text-muted-foreground text-center py-8">
                  No revisions yet.
                </p>
              )}
            </div>
          )}

          {selectedRevision && (
            <div className="flex flex-col gap-4">
              <div className="flex items-center justify-between">
                <Button variant="ghost" size="sm" onClick={() => setSelectedId(null)}>
                  <IconArrowLeft className="size-3" />
                  Back
                </Button>
                <Button
                  size="sm"
                  onClick={() => {
                    if (selectedRevision.htmlContent) {
                      onRestore(selectedRevision.htmlContent)
                      onOpenChange(false)
                      setSelectedId(null)
                    }
                  }}
                  disabled={!selectedRevision.htmlContent}
                >
                  Restore this version
                </Button>
              </div>
              <div className="flex items-center gap-2 text-sm text-muted-foreground">
                <span className="font-medium text-foreground">{selectedRevision.editedBy}</span>
                <span>·</span>
                <span>{updateTypeLabels[selectedRevision.updateType]}</span>
                <span>·</span>
                <span>
                  {new Date(selectedRevision.createdAt).toLocaleDateString("en-US", {
                    month: "short", day: "numeric", hour: "2-digit", minute: "2-digit",
                  })}
                </span>
              </div>
              <Separator />
              {diffHtml ? (
                <div
                  className="prose prose-sm dark:prose-invert max-w-none rounded-lg border p-4 bg-muted [&_ins]:bg-emerald-500/20 [&_ins]:text-emerald-900 [&_ins]:no-underline [&_ins]:px-0.5 [&_ins]:rounded-sm dark:[&_ins]:text-emerald-300 [&_del]:bg-red-500/20 [&_del]:text-red-900 [&_del]:line-through [&_del]:px-0.5 [&_del]:rounded-sm dark:[&_del]:text-red-300"
                  dangerouslySetInnerHTML={{ __html: diffHtml }}
                />
              ) : selectedRevision.htmlContent ? (
                <div
                  className="prose prose-sm dark:prose-invert max-w-none rounded-lg border p-4 bg-muted"
                  dangerouslySetInnerHTML={{ __html: selectedRevision.htmlContent }}
                />
              ) : (
                <p className="text-sm text-muted-foreground text-center py-8">
                  No content snapshot available for this revision.
                </p>
              )}
            </div>
          )}
        </div>
      </SheetContent>
    </Sheet>
  )
}
