# Add an entry here and run bin/rails typescript:constants. Labels stay in TypeScript,
# typed against the generated unions, so a missing label is a type error.
module TypescriptConstants
  OUTPUT = Rails.root.join("app/frontend/lib/generated/constants.ts")
  HEADER = "// Generated by bin/rails typescript:constants from Ruby constants. Do not edit.\n"

  Export = Data.define(:name, :value, :type_name)

  def self.exports
    [
      Export.new("LIFECYCLE_STAGES", {
        "TRIAGE" => IncidentLifecycleStage::TRIAGE, "ACTIVE" => IncidentLifecycleStage::ACTIVE,
        "CLOSED" => IncidentLifecycleStage::CLOSED, "CANCELED" => IncidentLifecycleStage::CANCELED
      }, nil),
      Export.new("DEFAULT_STATUS_SLUGS", {
        "TRIAGING" => IncidentStatus::SLUG_TRIAGING, "INVESTIGATING" => IncidentStatus::SLUG_INVESTIGATING,
        "IDENTIFIED" => IncidentStatus::SLUG_IDENTIFIED, "MONITORING" => IncidentStatus::SLUG_MONITORING,
        "RESOLVED" => IncidentStatus::SLUG_RESOLVED, "CANCELED" => IncidentStatus::SLUG_CANCELED
      }, nil),
      Export.new("INTEGRATION_CONNECT_WITH", { "CONNECTION_URL" => IntegrationProvider::CONNECT_CONNECTION_URL, "API_TOKEN" => IntegrationProvider::CONNECT_API_TOKEN }, nil),
      Export.new("INTEGRATION_KINDS", {
        "MCP" => Integration::KIND_MCP, "HTTP" => Integration::KIND_HTTP, "NATIVE" => Integration::KIND_NATIVE
      }, nil),
      Export.new("CUSTOM_MCP_PROVIDER_KEY", Integration::PROVIDER_CUSTOM_MCP, nil),
      Export.new("CONNECT_SCOPE_ALL", { "VALUE" => IntegrationProvider::ConnectField::ALL, "LABEL" => IntegrationProvider::ConnectField::ALL_LABEL }, nil),
      Export.new("RUNBOOK_QUERY_PARAM", Runbook::QUERY_PARAM, nil),
      Export.new("SIGN_IN_PROVIDERS", {
        "GOOGLE" => UserIdentity::GOOGLE, "SLACK" => UserIdentity::SLACK, "EMAIL" => UserIdentity::EMAIL
      }, nil),
      Export.new("INTEGRATION_DETAILS_QUERY_PARAM", Integration::DETAILS_QUERY_PARAM, nil),
      Export.new("INTEGRATION_CONNECT_QUERY_PARAM", Integration::CONNECT_QUERY_PARAM, nil),
      Export.new("INTEGRATION_CARD_ACTIONS", {
        "CONNECT" => IntegrationProvider::ACTION_CONNECT, "RECONNECT" => IntegrationProvider::ACTION_RECONNECT,
        "MANAGE" => IntegrationProvider::ACTION_MANAGE
      }, nil),
      Export.new("INSTALLATION_STATES", {
        "REMOVED" => Integrations::Installations::REMOVED, "SUSPENDED" => Integrations::Installations::SUSPENDED,
        "EMPTIED" => Integrations::Installations::EMPTIED
      }, nil),
      Export.new("INCIDENT_FORM_SLUGS", IncidentForm::SLUGS, "IncidentFormSlug"),
      Export.new("RESOURCE_MAP_KINDS", ResourceMap::KINDS, "ResourceMapKind"),
      Export.new("REMEDIATION_STEP_KINDS", Investigation::RemediationStep::KINDS, "RemediationStepKind"),
      Export.new("REMEDIATION_STEP_STATUSES", Investigation::RemediationStep::STATUSES, "RemediationStepStatus"),
      Export.new("REMEDIATION_PLAN_STATUSES", Investigation::RemediationPlan::STATUSES, "RemediationPlanStatus"),
      Export.new("REMEDIATION_STEP_STATUS_RUNNING", Investigation::RemediationStep::STATUS_RUNNING, nil),
      Export.new("HELD_CALL_STATUSES", {
        "WAITING" => Chat::HeldCall::STATUS_WAITING, "CHECKING" => Chat::HeldCall::STATUS_CHECKING, "READY" => Chat::HeldCall::STATUS_READY,
        "RUNNING" => Chat::HeldCall::STATUS_RUNNING, "RAN" => Chat::HeldCall::STATUS_RAN, "FAILED" => Chat::HeldCall::STATUS_FAILED,
        "DISMISSED" => Chat::HeldCall::STATUS_DISMISSED, "EXPIRED" => Chat::HeldCall::STATUS_EXPIRED, "DENIED" => Chat::HeldCall::STATUS_DENIED,
        "ASKED_AGAIN" => Chat::HeldCall::STATUS_ASKED_AGAIN
      }, nil),
      Export.new("WATCH_STATUSES", Chat::Watch::STATUSES.to_h { |status| [ status.upcase, status ] }, nil),
      Export.new("SECRET_ENTRY_KINDS", Chat::SecretEntry::KINDS.to_h { |kind| [ kind.upcase, kind ] }, nil),
      Export.new("RUNBOOK_CHOICE_PROPS", SettingsController::RUNBOOK_CHOICE_PROPS, nil),
      Export.new("RUNBOOK_FIELD_KINDS", Chat::Tools::Choices::KINDS.to_h { |kind| [ kind.upcase, kind ] }, nil),
      Export.new("WATCH_STEP_STATUSES", Chat::Watch::Step::STATUSES.to_h { |status| [ status.upcase, status ] }, nil),
      Export.new("PULL_REQUEST_NOTICE_STATUSES", CodeAgentSession::Notice::STATUSES.to_h { |status| [ status.upcase, status ] }, nil),
      Export.new("WATCH_TONES", Conversation::Watches::TONES.to_h { |tone| [ tone.upcase, tone ] }, nil),
      Export.new("APPROVED_CALL_ACTIONS", {
        "RUN" => Chat::CurrentState::ACTION_RUN, "DISMISS" => Chat::CurrentState::ACTION_DISMISS, "ASK_AGAIN" => Chat::CurrentState::ACTION_ASK_AGAIN
      }, nil),
      Export.new("PAST_INCIDENT_DAYS", Incident::Outcome::PAST_WINDOW_DAYS, nil),
      Export.new("CHAT_MEMORY_STATES", Chat::Memory::STATES, "ChatMemoryState"),
      Export.new("CHAT_MEMORY_STATE", Chat::Memory::STATES.index_by { |state| state.upcase }, nil),
      Export.new("CHAT_MEMORY_TEXT_LIMIT", Chat::Memory::TEXT_LIMIT, nil),
      Export.new("MEMORY_EXPIRY_DAY_CHOICES", Chat::Memory::EXPIRY_CHOICES, nil),
      Export.new("CHAT_INSTRUCTION_TEXT_LIMIT", Chat::Instruction::TEXT_LIMIT, nil),
      Export.new("MEMORY_PAGE_TABS", { "MEMORIES" => MemoryController::TAB_MEMORIES, "INSTRUCTIONS" => MemoryController::TAB_INSTRUCTIONS }, nil),
      Export.new("MEMORY_PAGE_TAB_QUERY", MemoryController::TAB_QUERY, nil),
      Export.new("MEMORY_QUERY_PARAM", Chat::Memory::QUERY_PARAM, nil),
      Export.new("CATALOG_ENTRY_QUERY_PARAM", CatalogEntry::QUERY_PARAM, nil),
      Export.new("RESOURCE_MAP_PAGE_QUERY", { "VIEW" => ResourceMap::PAGE_VIEW_PARAM, "RESOURCE" => ResourceMap::PAGE_RESOURCE_PARAM }, nil),
      Export.new("RESOURCE_MAP_VIEWS", { "MAP" => ResourceMap::VIEW_MAP, "FOCUS" => ResourceMap::VIEW_FOCUS, "TABLE" => ResourceMap::VIEW_TABLE }, nil),
      Export.new("MAP_SEARCH_TYPES", SearchDocument::Search::TYPES, "MapSearchType"),
      Export.new("MAP_SEARCH_TYPE", {
        "RESOURCE" => SearchDocument::Search::TYPE_RESOURCE, "CATALOG_ENTRY" => SearchDocument::Search::TYPE_CATALOG_ENTRY,
        "MEMORY" => SearchDocument::Search::TYPE_MEMORY
      }, nil),
      Export.new("RESOURCE_MAP_RELATIONS", ResourceMap::RELATIONS, "ResourceMapRelation"),
      Export.new("RESOURCE_MAP_RELATION", ResourceMap::RELATIONS.to_h { |relation| [ relation.upcase, relation ] }, nil),
      Export.new("RESOURCE_MAP_ORIGINS", ResourceMap::ORIGINS, "ResourceMapOrigin"),
      Export.new("RESOURCE_MAP_ORIGIN", ResourceMap::ORIGINS.to_h { |origin| [ origin.upcase, origin ] }, nil),
      Export.new("RESOURCE_MAP_CHANGE_KINDS", ResourceMap::Change::KINDS, "ResourceMapChangeKind"),
      Export.new("RESOURCE_MAP_HEALTHS", ResourceMap::Resource::HEALTHS, "ResourceMapHealth"),
      Export.new("RESOURCE_MAP_LOG_LEVELS", ResourceMap::LogMiner::LEVELS, "ResourceMapLogLevel"),
      Export.new("RESOURCE_MAP_CERTAINTIES", ResourceMap::CERTAINTIES, "ResourceMapCertainty"),
      Export.new("RESOURCE_MAP_CERTAINTY", { "LIKELY" => ResourceMap::CERTAINTY_LIKELY, "POSSIBLE" => ResourceMap::CERTAINTY_POSSIBLE }, nil),
      Export.new("RESOURCE_MAP_INCIDENT_WINDOW_DAYS", ResourceMap::View::INCIDENT_WINDOW.in_days.to_i, nil),
      Export.new("RESOURCE_MAP_CHANGE_WINDOW_HOURS", ResourceMap::View::CHANGE_WINDOW.in_hours.to_i, nil),
      Export.new("INCIDENT_RELATIONSHIPS", {
        "RELATED" => IncidentRelationship::RELATED, "DUPLICATE" => IncidentRelationship::DUPLICATE
      }, nil),
      Export.new("LEAD_ROLE_SLUG", IncidentRole::SLUG_INCIDENT_LEAD, nil),
      Export.new("CHANGE_KINDS", {
        "VALUE" => IncidentUpdate::CHANGE_KIND_VALUE, "TEXT" => IncidentUpdate::CHANGE_KIND_TEXT, "TIME" => IncidentUpdate::CHANGE_KIND_TIME
      }, nil),
      Export.new("ARCHIVE_CHANNEL_DELAY_CHOICES", Workspace::ARCHIVE_DELAY_CHOICES.map(&:to_h), nil),
      Export.new("ARCHIVE_CHANNEL_DELAY_NEVER", Workspace::ARCHIVE_DELAY_NEVER, nil),
      Export.new("CONDITION_FIELD_LABELS", IncidentCondition::FIELD_LABELS, nil),
      Export.new("CONDITION_OPERATOR_LABELS", IncidentCondition::OPERATOR_LABELS, nil),
      Export.new("ALERT_NORMALIZED_FIELDS", AlertProviders::Base::NORMALIZED_FIELDS, "AlertNormalizedField"),
      Export.new("ALERT_CONDITION_OPERATORS", PolicyRule::OPERATORS, "AlertConditionOperator"),
      Export.new("ALERT_OUTCOME_ACTIONS", PolicyRule::AlertRoutingOutcome::ACTIONS, "AlertOutcomeAction"),
      Export.new("ALERT_NOTIFY_TARGETS", {
        "MEMBER" => PolicyRule::AlertRoutingOutcome::TARGET_MEMBER,
        "TEAM" => PolicyRule::AlertRoutingOutcome::TARGET_TEAM,
        "OWNING_TEAM" => PolicyRule::AlertRoutingOutcome::TARGET_OWNING_TEAM,
        "CHANNEL" => PolicyRule::AlertRoutingOutcome::TARGET_CHANNEL
      }, nil),
      Export.new("ALERT_PROVIDERS", AlertSource::PROVIDERS, "AlertProvider"),
      Export.new("ABILITY_RESOURCES", Ability::Action::RESOURCES, "AbilityResource"),
      Export.new("ABILITY_GRANTABLE_RESOURCES", Ability::Action::GRANTABLE_RESOURCES, "AbilityGrantableResource"),
      Export.new("ABILITY_RESOURCE_LABELS", Ability::Action::RESOURCE_LABELS, nil),
      Export.new("ABILITY_ACTIONS", Ability::Action::ACTIONS, "AbilityAction"),
      Export.new("ABILITY_RESOURCE_ACTIONS", Ability::Action::GRANTABLE_RESOURCES.index_with { |resource| Ability::Action.actions_for(resource) }, nil),
      Export.new("WEBHOOK_EVENTS", Webhook::SUBSCRIBABLE_EVENTS, "WebhookEvent"),
      Export.new("ABILITY_RISK_LEVELS", Ability::Action::RISK_LEVELS, "AbilityRiskLevel"),
      Export.new("APPROVAL_HELD_RISK_LEVELS", Ability::Action::HELD_RISK_LEVELS, nil),
      Export.new("AGENT_STREAM_EVENTS", {
        "THINKING" => Conversation::LiveDelivery::EVENT_THINKING, "STEP" => Conversation::LiveDelivery::EVENT_STEP,
        "CHUNK" => Conversation::LiveDelivery::EVENT_CHUNK, "ANSWERED" => Conversation::LiveDelivery::EVENT_ANSWERED,
        "FAILED" => Conversation::LiveDelivery::EVENT_FAILED, "WAITING" => Conversation::LiveDelivery::EVENT_WAITING,
        "INVESTIGATION" => Conversation::LiveDelivery::EVENT_INVESTIGATION, "MADE_ROOM" => Conversation::LiveDelivery::EVENT_MADE_ROOM,
        "HELD_CALL" => Conversation::LiveDelivery::EVENT_HELD_CALL, "PACK_REFUSAL" => Conversation::LiveDelivery::EVENT_PACK_REFUSAL,
        "WATCH" => Conversation::LiveDelivery::EVENT_WATCH, "SECRET_ENTRY" => Conversation::LiveDelivery::EVENT_SECRET_ENTRY,
        "PULL_REQUEST" => Conversation::LiveDelivery::EVENT_PULL_REQUEST, "CODE_FIX" => Conversation::LiveDelivery::EVENT_CODE_FIX,
        "MEMORY" => Conversation::LiveDelivery::EVENT_MEMORY
      }, nil),
      Export.new("AGENT_STEP_STATUSES", {
        "RUNNING" => Conversation::LiveDelivery::STATUS_RUNNING, "DONE" => Conversation::LiveDelivery::STATUS_DONE,
        "WAITING" => Conversation::LiveDelivery::STATUS_WAITING, "CANCELLED" => Conversation::LiveDelivery::STATUS_CANCELLED,
        "FAILED" => Conversation::LiveDelivery::STATUS_FAILED, "NOT_FOUND" => Conversation::LiveDelivery::STATUS_NOT_FOUND,
        "REFUSED" => Conversation::LiveDelivery::STATUS_REFUSED
      }, nil),
      Export.new("STEP_OUTCOME_KINDS", {
        "ANSWERED" => Chat::StepOutcome::KIND_ANSWERED, "FAILED" => Chat::StepOutcome::KIND_FAILED,
        "NOT_FOUND" => Chat::StepOutcome::KIND_NOT_FOUND, "REFUSED" => Chat::StepOutcome::KIND_REFUSED
      }, nil),
      Export.new("CODE_FIX_LINE_RESULTS", {
        "PASSED" => Chat::CodeFixProgress::RESULT_PASSED, "FAILED" => Chat::CodeFixProgress::RESULT_FAILED
      }, nil),
      Export.new("CODE_FIX_OUTCOMES", {
        "OPENED" => Chat::CodeFixProgress::OUTCOME_OPENED, "PUSHED" => Chat::CodeFixProgress::OUTCOME_PUSHED, "FAILED" => Chat::CodeFixProgress::OUTCOME_FAILED,
        "PAUSED" => Chat::CodeFixProgress::OUTCOME_PAUSED
      }, nil),
      Export.new("CODE_FIX_PAUSE_STATUSES", {
        "OFFERED" => CodeAgentSession::Pause::STATUS_OFFERED, "CONTINUING" => CodeAgentSession::Pause::STATUS_CONTINUING,
        "STOPPED" => CodeAgentSession::Pause::STATUS_STOPPED
      }, nil),
      Export.new("CODE_AGENT_QUESTION_STATUSES", {
        "OPEN" => CodeAgentQuestion::STATUS_OPEN, "ANSWERED" => CodeAgentQuestion::STATUS_ANSWERED,
        "EXPIRED" => CodeAgentQuestion::STATUS_EXPIRED, "WITHDRAWN" => CodeAgentQuestion::STATUS_WITHDRAWN,
        "DEFAULTED" => CodeAgentQuestion::STATUS_DEFAULTED
      }, nil),
      Export.new("CODE_CHECK_STATUSES", {
        "PASSED" => Integrations::CodeChecks::PASSED, "FAILED" => Integrations::CodeChecks::FAILED, "TIMED_OUT" => Integrations::CodeChecks::TIMED_OUT,
        "COULD_NOT_RUN" => Integrations::CodeChecks::COULD_NOT_RUN
      }, nil),
      Export.new("AGENT_STEP_KINDS", {
        "READ" => Chat::Tools::KIND_READ, "ACT" => Chat::Tools::KIND_ACT, "ROOM" => Chat::Compaction::STEP_KIND
      }, nil),
      Export.new("AGENT_CARD_KINDS", {
        "INTEGRATIONS" => Chat::Tools::CARD_INTEGRATIONS, "INVESTIGATION" => Chat::Tools::CARD_INVESTIGATION,
        "CHART" => Chat::Tools::CARD_CHART
      }, nil),
      Export.new("INTEGRATION_CARD_STATES", {
        "CONNECTED" => IntegrationProvider::STATE_CONNECTED, "NEEDS_ATTENTION" => IntegrationProvider::STATE_NEEDS_ATTENTION,
        "TURNED_OFF" => IntegrationProvider::STATE_TURNED_OFF, "NOT_CONNECTED" => IntegrationProvider::STATE_NOT_CONNECTED
      }, nil),
      Export.new("AGENT_CHANNEL", ConversationChannel.name, nil),
      Export.new("AGENT_CHAT_PROPS", AgentChatsController::PROPS, nil),
      Export.new("SETUP_STEPS", {
        "ACCOUNT" => WorkspaceOnboarding::STEP_ACCOUNT, "AI" => WorkspaceOnboarding::STEP_AI, "STACK" => WorkspaceOnboarding::STEP_STACK,
        "PERMISSIONS" => WorkspaceOnboarding::STEP_PERMISSIONS, "HALON" => WorkspaceOnboarding::STEP_HALON,
        "SLACK" => WorkspaceOnboarding::STEP_SLACK, "TEST_INCIDENT" => WorkspaceOnboarding::STEP_TEST_INCIDENT
      }, nil),
      Export.new("SETUP_STEP_STATES", {
        "DONE" => WorkspaceOnboarding::STATE_DONE, "SKIPPED" => WorkspaceOnboarding::STATE_SKIPPED,
        "CURRENT" => WorkspaceOnboarding::STATE_CURRENT, "WAITING" => WorkspaceOnboarding::STATE_WAITING
      }, nil),
      Export.new("SETUP_AI_CHOICES", {
        "ACCOUNT" => WorkspaceOnboarding::AI_ACCOUNT, "CREDITS" => WorkspaceOnboarding::AI_CREDITS, "HOUSE" => WorkspaceOnboarding::AI_HOUSE
      }, nil),
      Export.new("SETUP_ANSWERS", { "CONNECTED" => WorkspaceOnboarding::ANSWER_CONNECTED, "UNUSED" => WorkspaceOnboarding::ANSWER_UNUSED }, nil),
      Export.new("INVESTIGATION_QUERY_PARAM", Investigation::QUERY_PARAM, nil),
      Export.new("INCIDENT_NAME_FIELD_KEY", IncidentSystemField::KEY_NAME, nil),
      Export.new("INVESTIGATION_EVENT_TYPES", IncidentEvent::INVESTIGATION_EVENTS, nil),
      Export.new("INVESTIGATION_PROP", InvestigationsController::PROP_INVESTIGATION, nil),
      Export.new("OPEN_INVESTIGATION_PROP", IncidentsController::PROP_OPEN_INVESTIGATION, nil),
      Export.new("INVESTIGATION_START_PROP", IncidentsController::PROP_INVESTIGATION_START, nil),
      Export.new("REOPEN_REASON_LIMIT", Incident::REOPEN_REASON_LIMIT, nil),
      Export.new("INVESTIGATION_STATUSES", Investigation::STATUSES, "InvestigationStatus"),
      Export.new("INVESTIGATION_LIVE_STATUSES", Investigation::LIVE_STATUSES, nil),
      Export.new("INVESTIGATION_TRIGGERS", Investigation::TRIGGER_SOURCES, "InvestigationTrigger"),
      Export.new("HYPOTHESIS_STATUSES", Investigation::Hypothesis::STATUSES, "HypothesisStatus"),
      Export.new("INVESTIGATION_STEP_STATUSES", Investigation::Step::STATUSES, "InvestigationStepStatus"),
      Export.new("HYPOTHESIS_STATUS", {
        "OPEN" => Investigation::Hypothesis::STATUS_OPEN, "SUPPORTED" => Investigation::Hypothesis::STATUS_SUPPORTED,
        "REFUTED" => Investigation::Hypothesis::STATUS_REFUTED
      }, nil),
      Export.new("INVESTIGATION_STEP_STATUS", {
        "PENDING" => Investigation::Step::STATUS_PENDING, "RUNNING" => Investigation::Step::STATUS_RUNNING,
        "SUCCEEDED" => Investigation::Step::STATUS_SUCCEEDED, "FAILED" => Investigation::Step::STATUS_FAILED
      }, nil),
      Export.new("FINDING_OUTCOMES", Investigation::Finding::OUTCOMES, "FindingOutcome"),
      Export.new("LEDGER_DECISIONS", Ability::Invocation::DECISIONS, "LedgerDecision"),
      Export.new("LEDGER_SOURCES", AbilityGateway::SOURCES, "LedgerSource"),
      Export.new("CHAT_MESSAGE_ROLES", {
        "USER" => Chat::Message::ROLE_USER, "ASSISTANT" => Chat::Message::ROLE_ASSISTANT
      }, nil),
      Export.new("CHAT_ATTACHMENT_KINDS", {
        "IMAGE" => Chat::Attachment::KIND_IMAGE, "PDF" => Chat::Attachment::KIND_PDF,
        "TEXT" => Chat::Attachment::KIND_TEXT, "UNREAD" => Chat::Attachment::KIND_UNREAD
      }, nil),
      Export.new("PRINCIPAL_KINDS", {
        "USER" => Ability::Principal::KIND_USER, "AGENT" => Ability::Principal::KIND_AGENT,
        "API_KEY" => Ability::Principal::KIND_API_KEY, "SYSTEM_AGENT" => Ability::Principal::KIND_SYSTEM_AGENT
      }, nil),
      Export.new("GRANT_KINDS", { "ACTION" => PrincipalSerializer::KIND_ACTION, "SET" => PrincipalSerializer::KIND_SET }, nil),
      Export.new("AI_ACCOUNT_STATES", WorkspaceAiAccount::STATES.to_h { |state| [ state.to_s.upcase, state.to_s ] }, nil),
      Export.new("APPROVAL_RUN_WINDOW_MINUTES", Ability::Approval::RUN_WINDOW.in_minutes.to_i, nil),
      Export.new("WATCH_SPEC_KEYS", Chat::Watch::SPEC_KEYS.transform_keys { |key| key.to_s.upcase }, nil),
      Export.new("IMPLICIT_AUTHORITIES", {
        "ADMIN" => Principal::IMPLICIT_ADMIN.to_s, "MEMBER" => Principal::IMPLICIT_MEMBER.to_s, "NONE" => Principal::IMPLICIT_NONE.to_s
      }, nil),
      Export.new("APPROVAL_NOTIFY_OPTIONS", PolicyRule::ApprovalOutcome::NOTIFY_OPTIONS, "ApprovalNotifyOption"),
      Export.new("APPROVER_ROLES", [ WorkspaceMembership.roles[:owner], WorkspaceMembership.roles[:admin] ], "ApproverRole"),
      Export.new("SANDBOX_SERVICES", CodeBox::SERVICES, "SandboxService")
    ]
  end

  def self.render
    exports.each_with_object(HEADER.dup) do |export, out|
      out << "\nexport const #{export.name} = #{JSON.pretty_generate(export.value)} as const\n"
      out << "export type #{export.type_name} = (typeof #{export.name})[number]\n" if export.type_name
    end
  end

  def self.write!
    OUTPUT.dirname.mkpath
    OUTPUT.write(render)
  end

  def self.current?
    OUTPUT.exist? && OUTPUT.read == render
  end
end
