# Add an entry here and run bin/rails typescript:constants. Labels stay in TypeScript,
# typed against the generated unions, so a missing label is a type error.
module TypescriptConstants
  OUTPUT = Rails.root.join("app/frontend/lib/generated/constants.ts")
  HEADER = "// Generated by bin/rails typescript:constants from Ruby constants. Do not edit.\n"

  Export = Data.define(:name, :value, :type_name)

  def self.exports
    [
      Export.new("LIFECYCLE_STAGES", {
        "TRIAGE" => IncidentLifecycleStage::TRIAGE, "ACTIVE" => IncidentLifecycleStage::ACTIVE,
        "CLOSED" => IncidentLifecycleStage::CLOSED, "CANCELED" => IncidentLifecycleStage::CANCELED
      }, nil),
      Export.new("INTEGRATION_CONNECT_WITH", { "CONNECTION_URL" => IntegrationProvider::CONNECT_CONNECTION_URL }, nil),
      Export.new("INTEGRATION_KINDS", {
        "MCP" => Integration::KIND_MCP, "HTTP" => Integration::KIND_HTTP, "NATIVE" => Integration::KIND_NATIVE
      }, nil),
      Export.new("CUSTOM_MCP_PROVIDER_KEY", Integration::PROVIDER_CUSTOM_MCP, nil),
      Export.new("RUNBOOK_QUERY_PARAM", Runbook::QUERY_PARAM, nil),
      Export.new("INTEGRATION_DETAILS_QUERY_PARAM", Integration::DETAILS_QUERY_PARAM, nil),
      Export.new("INTEGRATION_CONNECT_QUERY_PARAM", Integration::CONNECT_QUERY_PARAM, nil),
      Export.new("INTEGRATION_CARD_ACTIONS", {
        "CONNECT" => IntegrationProvider::ACTION_CONNECT, "RECONNECT" => IntegrationProvider::ACTION_RECONNECT,
        "MANAGE" => IntegrationProvider::ACTION_MANAGE
      }, nil),
      Export.new("INCIDENT_FORM_SLUGS", IncidentForm::SLUGS, "IncidentFormSlug"),
      Export.new("INCIDENT_RELATIONSHIPS", {
        "RELATED" => IncidentRelationship::RELATED, "DUPLICATE" => IncidentRelationship::DUPLICATE
      }, nil),
      Export.new("LEAD_ROLE_SLUG", IncidentRole::SLUG_INCIDENT_LEAD, nil),
      Export.new("CHANGE_KINDS", {
        "VALUE" => IncidentUpdate::CHANGE_KIND_VALUE, "TEXT" => IncidentUpdate::CHANGE_KIND_TEXT, "TIME" => IncidentUpdate::CHANGE_KIND_TIME
      }, nil),
      Export.new("ARCHIVE_CHANNEL_DELAY_CHOICES", Workspace::ARCHIVE_DELAY_CHOICES.map(&:to_h), nil),
      Export.new("ARCHIVE_CHANNEL_DELAY_NEVER", Workspace::ARCHIVE_DELAY_NEVER, nil),
      Export.new("CONDITION_FIELD_LABELS", IncidentCondition::FIELD_LABELS, nil),
      Export.new("CONDITION_OPERATOR_LABELS", IncidentCondition::OPERATOR_LABELS, nil),
      Export.new("ALERT_NORMALIZED_FIELDS", AlertProviders::Base::NORMALIZED_FIELDS, "AlertNormalizedField"),
      Export.new("ALERT_CONDITION_OPERATORS", PolicyRule::OPERATORS, "AlertConditionOperator"),
      Export.new("ALERT_OUTCOME_ACTIONS", PolicyRule::AlertRoutingOutcome::ACTIONS, "AlertOutcomeAction"),
      Export.new("ALERT_NOTIFY_TARGETS", {
        "MEMBER" => PolicyRule::AlertRoutingOutcome::TARGET_MEMBER,
        "TEAM" => PolicyRule::AlertRoutingOutcome::TARGET_TEAM,
        "OWNING_TEAM" => PolicyRule::AlertRoutingOutcome::TARGET_OWNING_TEAM,
        "CHANNEL" => PolicyRule::AlertRoutingOutcome::TARGET_CHANNEL
      }, nil),
      Export.new("ALERT_PROVIDERS", AlertSource::PROVIDERS, "AlertProvider"),
      Export.new("ABILITY_RESOURCES", Ability::Action::RESOURCES, "AbilityResource"),
      Export.new("ABILITY_GRANTABLE_RESOURCES", Ability::Action::GRANTABLE_RESOURCES, "AbilityGrantableResource"),
      Export.new("ABILITY_RESOURCE_LABELS", Ability::Action::RESOURCE_LABELS, nil),
      Export.new("ABILITY_ACTIONS", Ability::Action::ACTIONS, "AbilityAction"),
      Export.new("WEBHOOK_EVENTS", Webhook::SUBSCRIBABLE_EVENTS, "WebhookEvent"),
      Export.new("ABILITY_RISK_LEVELS", Ability::Action::RISK_LEVELS, "AbilityRiskLevel"),
      Export.new("AGENT_STREAM_EVENTS", {
        "THINKING" => Conversation::LiveDelivery::EVENT_THINKING, "STEP" => Conversation::LiveDelivery::EVENT_STEP,
        "CHUNK" => Conversation::LiveDelivery::EVENT_CHUNK, "ANSWERED" => Conversation::LiveDelivery::EVENT_ANSWERED,
        "FAILED" => Conversation::LiveDelivery::EVENT_FAILED, "WAITING" => Conversation::LiveDelivery::EVENT_WAITING,
        "INVESTIGATION" => Conversation::LiveDelivery::EVENT_INVESTIGATION
      }, nil),
      Export.new("AGENT_STEP_STATUSES", {
        "RUNNING" => Conversation::LiveDelivery::STATUS_RUNNING, "DONE" => Conversation::LiveDelivery::STATUS_DONE,
        "WAITING" => Conversation::LiveDelivery::STATUS_WAITING, "CANCELLED" => Conversation::LiveDelivery::STATUS_CANCELLED,
        "FAILED" => Conversation::LiveDelivery::STATUS_FAILED
      }, nil),
      Export.new("AGENT_STEP_KINDS", {
        "READ" => Chat::Tools::KIND_READ, "ACT" => Chat::Tools::KIND_ACT
      }, nil),
      Export.new("AGENT_CARD_KINDS", {
        "INTEGRATIONS" => Chat::Tools::CARD_INTEGRATIONS, "INVESTIGATION" => Chat::Tools::CARD_INVESTIGATION
      }, nil),
      Export.new("INTEGRATION_CARD_STATES", {
        "CONNECTED" => IntegrationProvider::STATE_CONNECTED, "NEEDS_ATTENTION" => IntegrationProvider::STATE_NEEDS_ATTENTION,
        "TURNED_OFF" => IntegrationProvider::STATE_TURNED_OFF, "NOT_CONNECTED" => IntegrationProvider::STATE_NOT_CONNECTED
      }, nil),
      Export.new("AGENT_CHANNEL", ConversationChannel.name, nil),
      Export.new("AGENT_CHAT_PROPS", AgentChatsController::PROPS, nil),
      Export.new("INVESTIGATION_QUERY_PARAM", Investigation::QUERY_PARAM, nil),
      Export.new("INCIDENT_NAME_FIELD_KEY", IncidentSystemField::KEY_NAME, nil),
      *Operator::TypescriptConstants.exports.map { |name, value| Export.new(name, value, nil) },
      Export.new("INVESTIGATION_EVENT_TYPES", IncidentEvent::INVESTIGATION_EVENTS, nil),
      Export.new("INVESTIGATION_PROP", InvestigationsController::PROP_INVESTIGATION, nil),
      Export.new("OPEN_INVESTIGATION_PROP", IncidentsController::PROP_OPEN_INVESTIGATION, nil),
      Export.new("INVESTIGATION_STATUSES", Investigation::STATUSES, "InvestigationStatus"),
      Export.new("INVESTIGATION_LIVE_STATUSES", Investigation::LIVE_STATUSES, nil),
      Export.new("INVESTIGATION_TRIGGERS", Investigation::TRIGGER_SOURCES, "InvestigationTrigger"),
      Export.new("HYPOTHESIS_STATUSES", Investigation::Hypothesis::STATUSES, "HypothesisStatus"),
      Export.new("INVESTIGATION_STEP_STATUSES", Investigation::Step::STATUSES, "InvestigationStepStatus"),
      Export.new("HYPOTHESIS_STATUS", {
        "OPEN" => Investigation::Hypothesis::STATUS_OPEN, "SUPPORTED" => Investigation::Hypothesis::STATUS_SUPPORTED,
        "REFUTED" => Investigation::Hypothesis::STATUS_REFUTED
      }, nil),
      Export.new("INVESTIGATION_STEP_STATUS", {
        "PENDING" => Investigation::Step::STATUS_PENDING, "RUNNING" => Investigation::Step::STATUS_RUNNING,
        "SUCCEEDED" => Investigation::Step::STATUS_SUCCEEDED, "FAILED" => Investigation::Step::STATUS_FAILED
      }, nil),
      Export.new("FINDING_OUTCOMES", Investigation::Finding::OUTCOMES, "FindingOutcome"),
      Export.new("LEDGER_DECISIONS", Ability::Invocation::DECISIONS, "LedgerDecision"),
      Export.new("CHAT_MESSAGE_ROLES", {
        "USER" => Chat::Message::ROLE_USER, "ASSISTANT" => Chat::Message::ROLE_ASSISTANT
      }, nil),
      Export.new("PRINCIPAL_KINDS", {
        "USER" => Ability::Principal::KIND_USER, "AGENT" => Ability::Principal::KIND_AGENT,
        "API_KEY" => Ability::Principal::KIND_API_KEY, "SYSTEM_AGENT" => Ability::Principal::KIND_SYSTEM_AGENT
      }, nil),
      Export.new("APPROVAL_NOTIFY_OPTIONS", PolicyRule::ApprovalOutcome::NOTIFY_OPTIONS, "ApprovalNotifyOption"),
      Export.new("APPROVER_ROLES", [ WorkspaceMembership.roles[:owner], WorkspaceMembership.roles[:admin] ], "ApproverRole")
    ]
  end

  def self.render
    exports.each_with_object(HEADER.dup) do |export, out|
      out << "\nexport const #{export.name} = #{JSON.pretty_generate(export.value)} as const\n"
      out << "export type #{export.type_name} = (typeof #{export.name})[number]\n" if export.type_name
    end
  end

  def self.write!
    OUTPUT.dirname.mkpath
    OUTPUT.write(render)
  end

  def self.current?
    OUTPUT.exist? && OUTPUT.read == render
  end
end
