# Ruby constants the dashboard renders from, emitted as one generated module
# so the two sides cannot drift. Add an entry here and run
# bin/rails typescript:constants. Labels stay in TypeScript, typed against
# the generated unions, so a missing label is a type error.
module TypescriptConstants
  OUTPUT = Rails.root.join("app/frontend/lib/generated/constants.ts")
  HEADER = "// Generated by bin/rails typescript:constants from Ruby constants. Do not edit.\n"

  Export = Data.define(:name, :value, :type_name)

  def self.exports
    [
      Export.new("LIFECYCLE_STAGES", {
        "TRIAGE" => IncidentLifecycleStage::TRIAGE, "ACTIVE" => IncidentLifecycleStage::ACTIVE,
        "CLOSED" => IncidentLifecycleStage::CLOSED, "CANCELED" => IncidentLifecycleStage::CANCELED
      }, nil),
      Export.new("INTEGRATION_KINDS", {
        "MCP" => Integration::KIND_MCP, "HTTP" => Integration::KIND_HTTP, "NATIVE" => Integration::KIND_NATIVE
      }, nil),
      Export.new("CUSTOM_MCP_PROVIDER_KEY", Integration::PROVIDER_CUSTOM_MCP, nil),
      Export.new("ALERT_NORMALIZED_FIELDS", AlertProviders::Base::NORMALIZED_FIELDS, "AlertNormalizedField"),
      Export.new("ALERT_CONDITION_OPERATORS", PolicyRule::OPERATORS, "AlertConditionOperator"),
      Export.new("ALERT_OUTCOME_ACTIONS", PolicyRule::AlertRoutingOutcome::ACTIONS, "AlertOutcomeAction"),
      Export.new("ALERT_NOTIFY_TARGETS", {
        "MEMBER" => PolicyRule::AlertRoutingOutcome::TARGET_MEMBER,
        "TEAM" => PolicyRule::AlertRoutingOutcome::TARGET_TEAM,
        "OWNING_TEAM" => PolicyRule::AlertRoutingOutcome::TARGET_OWNING_TEAM,
        "CHANNEL" => PolicyRule::AlertRoutingOutcome::TARGET_CHANNEL
      }, nil),
      Export.new("ALERT_PROVIDERS", AlertSource::PROVIDERS, "AlertProvider"),
      Export.new("ABILITY_RESOURCES", Ability::Action::RESOURCES, "AbilityResource"),
      Export.new("ABILITY_GRANTABLE_RESOURCES", Ability::Action::GRANTABLE_RESOURCES, "AbilityGrantableResource"),
      Export.new("ABILITY_RESOURCE_LABELS", Ability::Action::RESOURCE_LABELS, nil),
      Export.new("ABILITY_ACTIONS", Ability::Action::ACTIONS, "AbilityAction"),
      Export.new("WEBHOOK_EVENTS", Webhook::SUBSCRIBABLE_EVENTS, "WebhookEvent"),
      Export.new("ABILITY_RISK_LEVELS", Ability::Action::RISK_LEVELS, "AbilityRiskLevel"),
      Export.new("PRINCIPAL_KINDS", {
        "USER" => Ability::Principal::KIND_USER, "AGENT" => Ability::Principal::KIND_AGENT, "API_KEY" => Ability::Principal::KIND_API_KEY
      }, nil),
      Export.new("APPROVAL_NOTIFY_OPTIONS", PolicyRule::ApprovalOutcome::NOTIFY_OPTIONS, "ApprovalNotifyOption"),
      Export.new("APPROVER_ROLES", [ WorkspaceMembership.roles[:owner], WorkspaceMembership.roles[:admin] ], "ApproverRole")
    ]
  end

  def self.render
    exports.each_with_object(HEADER.dup) do |export, out|
      out << "\nexport const #{export.name} = #{JSON.pretty_generate(export.value)} as const\n"
      out << "export type #{export.type_name} = (typeof #{export.name})[number]\n" if export.type_name
    end
  end

  def self.write!
    OUTPUT.dirname.mkpath
    OUTPUT.write(render)
  end

  def self.current?
    OUTPUT.exist? && OUTPUT.read == render
  end
end
