module Identifiers
  # Modal callback_ids
  INCIDENT_CREATION_MODAL = "incident_creation_modal"
  INCIDENT_HOME_MODAL = "incident_home_modal"
  SHARE_INCIDENTS_CHANNEL_MODAL = "share_incidents_channel_modal"
  UPDATE_SUMMARY_MODAL = "update_summary_modal"
  SET_LEAD_MODAL = "set_lead_modal"
  INCIDENT_UPDATE_MODAL = "incident_update_modal"
  SEND_INCIDENT_UPDATE = "send_incident_update"
  INCIDENT_ACTIONS_MODAL = "incident_actions_modal"
  INCIDENT_FOLLOWUPS_MODAL = "incident_followups_modal"
  CREATE_ACTION_MODAL = "create_action_modal"
  CREATE_FOLLOWUP_MODAL = "create_followup_modal"
  CLOSE_INCIDENT_MODAL = "close_incident_modal"
  REOPEN_INCIDENT_MODAL = "reopen_incident_modal"
  LINK_INCIDENT_MODAL = "link_incident_modal"
  ESCALATE_INCIDENT_MODAL = "escalate_incident_modal"
  INVITE_RESPONDERS_MODAL = "invite_responders_modal"
  SHOUTOUT_MODAL = "shoutout_modal"

  # Shortcut callback_ids
  CREATE_INCIDENT_SHORTCUT = "create_incident_shortcut"

  # Slash command subcommands
  SUBCOMMAND_NEW        = "new"
  SUBCOMMAND_HOME       = "home"
  SUBCOMMAND_SUMMARY    = "summary"
  SUBCOMMAND_LEAD       = "lead"
  SUBCOMMAND_STATUS     = "status"
  SUBCOMMAND_UPDATE     = "update"
  SUBCOMMAND_SEVERITY   = "severity"
  SUBCOMMAND_ESCALATE   = "escalate"
  SUBCOMMAND_INVITE     = "invite"
  SUBCOMMAND_ACTION     = "action"
  SUBCOMMAND_ACTIONS    = "actions"
  SUBCOMMAND_FOLLOWUP   = "followup"
  SUBCOMMAND_FOLLOWUPS  = "followups"
  SUBCOMMAND_LINK       = "link"
  SUBCOMMAND_RELATE     = "relate"
  SUBCOMMAND_DUPLICATE  = "duplicate"
  SUBCOMMAND_CLOSE      = "close"
  SUBCOMMAND_RESOLVE    = "resolve"
  SUBCOMMAND_REOPEN     = "reopen"
  SUBCOMMAND_POSTMORTEM = "postmortem"
  SUBCOMMAND_TIMELINE   = "timeline"
  SUBCOMMAND_LIST       = "list"
  SUBCOMMAND_SHOUTOUT   = "shoutout"

  # Home modal action values
  HOME_ACTION_NEW        = "new"
  HOME_ACTION_STATUS     = "status"
  HOME_ACTION_SEVERITY   = "severity"
  HOME_ACTION_SUMMARY    = "summary"
  HOME_ACTION_ESCALATE   = "escalate"
  HOME_ACTION_INVITE     = "invite"
  HOME_ACTION_LEAD       = "lead"
  HOME_ACTION_ACTIONS    = "actions"
  HOME_ACTION_CLOSE      = "close"
  HOME_ACTION_TIMELINE   = "timeline"
  HOME_ACTION_LIST       = "list"
  HOME_ACTION_POSTMORTEM = "postmortem"

  # Block action_ids
  HOME_ACTION_SELECT = "home_action_select"
  SHARE_INCIDENTS_CHANNEL = "share_incidents_channel"
  PREVIEW_ANNOUNCEMENT = "preview_announcement"
  PREVIEW_HOMEPAGE_DISABLED = "preview_homepage_disabled"
  PREVIEW_SUBSCRIBE_DISABLED = "preview_subscribe_disabled"
  SET_INCIDENT_LEAD_SELF = "set_incident_lead_self"
  UPDATE_INCIDENT_SUMMARY = "update_incident_summary"
  ESCALATE_INCIDENT = "escalate_incident"
  PICK_UP_ACTION = "pick_up_action"
  MARK_ACTION_DONE = "mark_action_done"
  ADD_NEW_ACTION = "add_new_action"
  ADD_NEW_FOLLOWUP = "add_new_followup"
  CREATE_ACTION_FROM_REACTION = "create_action_from_reaction"
  CREATE_FOLLOWUP_FROM_REACTION = "create_followup_from_reaction"
  LOAD_MORE_TIMELINE = "load_more_timeline"
  ACKNOWLEDGE_ESCALATION = "acknowledge_escalation"
  SHOUTOUT_FROM_REACTION = "shoutout_from_reaction"
end
