class PostmortemUpdate < ApplicationRecord
  GENERATED = "generated"
  # A person started from an empty document rather than asking AI to draft it.
  STARTED = "started"
  EDITED = "edited"

  UPDATE_TYPES = [ GENERATED, STARTED, EDITED ].freeze
  LABELS = { GENERATED => "Generated by AI", STARTED => "Started blank", EDITED => "Edited" }.freeze

  include Recordable
  records Postmortem, recorder: :edited_by

  belongs_to :postmortem
  belongs_to :incident
  belongs_to :edited_by, polymorphic: true

  validates :update_type, presence: true, inclusion: { in: UPDATE_TYPES }
  validates :title, presence: true
  validates :content, presence: true
  validates :status, presence: true, inclusion: { in: ->(_) { Postmortem::STATUSES } }

  def label = LABELS.fetch(update_type)

  scope :ordered, -> { order(:created_at) }
end
