require "application_system_test_case"

class DashboardLinksTest < ApplicationSystemTestCase
  EXTERNAL_URL = "https://dash.cloudflare.com/acme/example.com/security/waf".freeze

  setup do
    @workspace = workspaces(:slack_workspace_one)
    FeatureFlags.enable!(@workspace, FeatureFlags::AI_SRE)
    Entitlements.stubs(:allows?).returns(true)
    sign_in(users(:alice), @workspace)
  end

  test "a link in Halon's answer to another site opens in a new tab, a dashboard link stays in this one" do
    conversation = Conversation.start_personal!(workspace: @workspace, member: workspace_memberships(:alice_workspace_one))
    conversation.ask!("where do I block that IP")
    conversation.chat.messages.create!(role: Chat::Message::ROLE_ASSISTANT, content: "")
    conversation.note!("Add a rule in the [Cloudflare dashboard](#{EXTERNAL_URL}), then check [the incident](/incidents).")
    conversation.reply_delivered!

    visit agent_chat_path(conversation)

    assert_selector "a[href='#{EXTERNAL_URL}'][target='_blank'][rel='noopener noreferrer']", text: "Cloudflare dashboard"
    assert_selector "a[href='/incidents']:not([target]):not([rel])", text: "the incident"
    page.save_screenshot(Rails.root.join("tmp/screenshots/agent-answer-links.png"))
  end

  test "a link in a postmortem revision to another site opens in a new tab, a dashboard link stays in this one" do
    html = %(<p>Blocked at the <a href="#{EXTERNAL_URL}">Cloudflare dashboard</a>, see <a href="/incidents">the incident</a>.</p>)
    postmortems(:postmortem_resolved_ws1).update!(content: { "html" => html })
    postmortem_updates(:postmortem_update_generated_ws1).update!(content: { "html" => html })

    visit incident_postmortem_path(incidents(:resolved_minor_ws1))
    click_on "Revisions"
    click_on "Generated by AI"

    within("[role='dialog']") do
      assert_selector "a[href='#{EXTERNAL_URL}'][target='_blank'][rel='noopener noreferrer']", text: "Cloudflare dashboard"
      assert_selector "a[href='/incidents']:not([target])", text: "the incident"
    end
    page.save_screenshot(Rails.root.join("tmp/screenshots/postmortem-revision-links.png"))
  end
end
