require "application_system_test_case"

class PostmortemRevisionsTest < ApplicationSystemTestCase
  PHONES = [ [ 390, 844 ], [ 320, 640 ] ].freeze

  setup do
    @workspace = workspaces(:slack_workspace_one)
    @member = workspace_memberships(:alice_workspace_one)
    Entitlements.stubs(:allows?).returns(true)
    @incident = Incident.create!(
      workspace: @workspace, declared_by: @member, incident_status: incident_statuses(:resolved_ws1),
      incident_severity: incident_severities(:minor_ws1), name: "Checkout failing", is_private: false,
      resolved_at: Time.current, source: Incident::SOURCE_SLACK
    )
    postmortem = Postmortem.start_blank!(@incident, by: @member)
    postmortem.update_content!("<h2>Summary</h2><p>Payments timed out after the deploy.</p>", by: @member, expected_version: postmortem.content_version)
    sign_in(users(:alice), @workspace)
  end

  test "a blank start reads as one in the revisions, and Restore this version fits on a wide screen and a phone" do
    visit incident_postmortem_path(@incident)
    click_on "Revisions"

    within("[role='dialog']") do
      assert_text "Started blank"
      assert_text "Edited"
      assert_no_text "Generated by AI"
    end
    page.save_screenshot(Rails.root.join("tmp/screenshots/postmortem-revisions-list.png"))

    click_on "Edited"
    assert_restore_fits
    page.save_screenshot(Rails.root.join("tmp/screenshots/postmortem-revision-restore.png"))

    PHONES.each do |width, height|
      page.current_window.resize_to(width, height)
      assert_restore_fits
      assert_no_page_scroll_sideways
      page.save_screenshot(Rails.root.join("tmp/screenshots/postmortem-revision-restore-#{width}.png"))
    end
  end

  private

  # The whole button sits inside the sheet, so nothing of it is cut off by the sheet's edge.
  def assert_restore_fits
    button = find("button", text: "Restore this version")
    inside = evaluate_script(<<~JS, button)
      ((button) => {
        const sheet = button.closest("[role='dialog']").getBoundingClientRect()
        const box = button.getBoundingClientRect()
        const label = button.scrollWidth <= button.clientWidth
        return label && box.left >= sheet.left && box.right <= sheet.right && box.top >= sheet.top && box.bottom <= sheet.bottom
      })(arguments[0])
    JS
    assert inside, "Restore this version is cut off by the sheet"
  end

  def assert_no_page_scroll_sideways
    assert evaluate_script("document.documentElement.scrollWidth <= window.innerWidth"), "the page scrolls sideways"
  end
end
